(function(){
"use strict";
var STORE="giess_check_garten_v3",SYNC_STORE="johannas_gartenwelt_sync_v1";
var specs={
 plant:{input:"plantPhoto",form:"plantForm",place:"saveAndPlaceBtn",draft:"photoData",edit:"editPlantId",list:"plants",folder:"plants"},
 habitat:{input:"habitatPhoto",form:"habitatForm",place:"saveHabitatAndPlaceBtn",draft:"habitatPhotoData",edit:"editHabitatId",list:"habitats",folder:"habitats"},
 animal:{input:"animalPhoto",form:"animalForm",place:"saveAnimalAndPlaceBtn",draft:"animalPhotoData",edit:"editAnimalId",list:"animals",folder:"animals"}
};
var pending={},bypass={};
function cfg(){try{return JSON.parse(localStorage.getItem(SYNC_STORE)||"{}")}catch(e){return{}}}
function configured(c){return !!(c&&c.enabled&&/^https:\/\/[^/]+\.supabase\.co$/i.test(String(c.url||"").replace(/\/+$/,""))&&String(c.key||"").length>10&&String(c.gardenId||"").length>=6&&String(c.pin||"").length>=6)}
async function sha256(s){var b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return Array.from(new Uint8Array(b)).map(function(x){return x.toString(16).padStart(2,"0")}).join("")}
async function secret(c){return sha256(String(c.gardenId||"").trim().toLowerCase()+"|"+String(c.pin||""))}
async function api(action,extra){var c=cfg();if(!configured(c))throw new Error("Geräte-Sync ist noch nicht vollständig eingerichtet.");var u=String(c.url).replace(/\/+$/,""),body=Object.assign({action:action,garden_id:String(c.gardenId).trim().toLowerCase(),secret_hash:await secret(c)},extra||{});var r=await fetch(u+"/functions/v1/jgw-photo",{method:"POST",headers:{"Content-Type":"application/json","apikey":c.key},body:JSON.stringify(body)}),t=await r.text(),d={};try{d=t?JSON.parse(t):{}}catch(e){}if(!r.ok||!d.ok)throw new Error(d.error||("HTTP "+r.status));return d}
function dataUrlToBlob(data){var p=String(data||"").split(","),m=(p[0].match(/data:([^;]+)/)||[])[1]||"image/jpeg",bin=atob(p[1]||""),a=new Uint8Array(bin.length);for(var i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return new Blob([a],{type:m})}
function compressSource(src,max,q){return new Promise(function(resolve,reject){var img=new Image(),url=typeof src==="string"?src:URL.createObjectURL(src),revoke=typeof src!=="string";img.onload=function(){var w=img.width,h=img.height;if(w>h&&w>max){h=Math.round(h*max/w);w=max}else if(h>=w&&h>max){w=Math.round(w*max/h);h=max}var c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(img,0,0,w,h);if(revoke)URL.revokeObjectURL(url);resolve(c.toDataURL("image/jpeg",q))};img.onerror=function(){if(revoke)URL.revokeObjectURL(url);reject(new Error("Foto konnte nicht verarbeitet werden."))};img.src=url})}
function localPayload(){var s=window.state||{};return{plz:s.plz,loc:s.loc,gardenCenter:s.gardenCenter,plants:s.plants||[],habitats:s.habitats||[],animals:s.animals||[],areas:s.areas||[],zones:s.zones||[],ecology:s.ecology,settings:s.settings,days:s.days}}
function persist(){localStorage.setItem(STORE,JSON.stringify(localPayload()))}
function dirty(){try{var c=cfg();if(c.enabled){c.dirty=true;localStorage.setItem(SYNC_STORE,JSON.stringify(c))}}catch(e){}}
function render(){try{if(window.JGWCore){JGWCore.renderPlants&&JGWCore.renderPlants();JGWCore.renderHabitats&&JGWCore.renderHabitats();JGWCore.renderAnimals&&JGWCore.renderAnimals()}}catch(e){}}
async function uploadData(data,folder,id){var d=await api("upload",{path:folder+"/"+id+".jpg",mime_type:"image/jpeg",data:data});var s=await api("sign",{ref:d.ref});return{ref:d.ref,url:s.url}}
function uniqueId(){return Date.now().toString(36)+Math.random().toString(36).slice(2,9)}
function itemByPhoto(list,url,id){var a=(window.state&&window.state[list])||[];if(id){var x=a.find(function(v){return String(v.id)===String(id)});if(x)return x}for(var i=a.length-1;i>=0;i--)if(a[i].photo===url)return a[i];return null}
async function prepare(type,file){var sp=specs[type],strong=await compressSource(file,640,.62),c=cfg();if(!configured(c))return{data:strong};var id=(window.state&&window.state[sp.edit])||uniqueId();try{return await uploadData(strong,sp.folder,id)}catch(e){console.warn("Fotospeicher",e);return{data:strong,error:e}}
function attachAfter(type,res,oldId,oldRef){setTimeout(function(){var sp=specs[type],it=itemByPhoto(sp.list,res.url||res.data,oldId);if(!it)return;if(res.ref){it.photoRef=res.ref;it.photo=res.url;if(oldRef&&oldRef!==res.ref)api("delete",{ref:oldRef}).catch(function(){})}else if(oldRef){it.photoRef=oldRef}try{persist();dirty()}catch(e){}render()},0)}
function intercept(type,event,trigger){if(bypass[type])return;var sp=specs[type],st=window.state||{},oldId=st[sp.edit]||null,arr=st[sp.list]||[],old=oldId?arr.find(function(x){return String(x.id)===String(oldId)}):null,oldRef=old&&old.photoRef||"",p=pending[type];if(!p){if(oldRef)setTimeout(function(){var it=itemByPhoto(sp.list,old&&old.photo,oldId);if(it&&!it.photoRef){it.photoRef=oldRef;try{persist();dirty()}catch(e){}}},0);return}event.preventDefault();event.stopImmediatePropagation();(async function(){var res=await p;pending[type]=null;st[sp.draft]=res.url||res.data;bypass[type]=true;try{if(trigger==="submit")document.getElementById(sp.form).requestSubmit();else document.getElementById(sp.place).click()}finally{bypass[type]=false}attachAfter(type,res,oldId,oldRef);if(res.error&&String(res.error.message||res.error).indexOf("Sync")<0)console.warn(res.error)})().catch(function(e){pending[type]=null;alert("Foto konnte nicht gespeichert werden: "+e.message)})}
function bindType(type){var sp=specs[type],input=document.getElementById(sp.input),form=document.getElementById(sp.form),place=document.getElementById(sp.place);if(input)input.addEventListener("change",function(){var f=this.files&&this.files[0];if(f)pending[type]=prepare(type,f)},true);if(form)form.addEventListener("submit",function(e){intercept(type,e,"submit")},true);if(place)place.addEventListener("click",function(e){intercept(type,e,"place")},true)}
async function refreshSigned(){var st=window.state||{},changed=false;for(var k of ["plants","habitats","animals"]){for(var it of (st[k]||[])){if(it.photoRef){try{var s=await api("sign",{ref:it.photoRef});if(s.url&&it.photo!==s.url){it.photo=s.url;changed=true}}catch(e){console.warn("Foto-URL",e)}}}}if(changed)render()}
function inlineCount(){var st=window.state||{},n=0,b=0;["plants","habitats","animals"].forEach(function(k){(st[k]||[]).forEach(function(it){if(/^data:image\//.test(String(it.photo||""))){n++;b+=String(it.photo).length}})});return{count:n,bytes:b}}
async function optimize(){var c=cfg(),cloud=configured(c),st=window.state||{},total=inlineCount(),done=0,failed=0,btn=document.getElementById("optimizePhotoStorageBtn"),status=document.getElementById("photoStorageStatus");if(!total.count){if(status)status.textContent="Keine eingebetteten Fotos mehr vorhanden.";return}if(btn){btn.disabled=true;btn.textContent="Fotos werden optimiert …"}for(var specName of ["plant","habitat","animal"]){var sp=specs[specName];for(var it of (st[sp.list]||[])){if(!/^data:image\//.test(String(it.photo||"")))continue;try{var compact=await compressSource(it.photo,640,.62);if(cloud){var up=await uploadData(compact,sp.folder,it.id||uniqueId());it.photoRef=up.ref;it.photo=up.url}else it.photo=await compressSource(it.photo,480,.54);done++;try{persist()}catch(e){}}catch(e){failed++;console.warn("Optimierung",e)}if(status)status.textContent="Optimiert: "+done+" von "+total.count+(failed?" · Fehler: "+failed:"")}}}try{persist();dirty()}catch(e){}if(btn){btn.disabled=false;btn.textContent="Speicher optimieren"}if(status)status.textContent=(cloud?"Cloud-Fotospeicher aktiv. ":"Lokal verkleinert. ")+done+" Fotos optimiert"+(failed?", "+failed+" nicht verarbeitet.":".");var ge=document.getElementById("globalError");if(ge&&ge.textContent.indexOf("Lokaler Speicher ist voll")>=0)ge.classList.add("hidden");setTimeout(function(){location.reload()},900)}
function installSettings(){var btn=document.getElementById("optimizePhotoStorageBtn");if(btn){if(!btn.dataset.storageBound){btn.dataset.storageBound="1";btn.addEventListener("click",optimize)}updateStatus();return}var exp=document.getElementById("exportBtn");if(!exp)return;var actions=exp.closest(".actions"),box=actions&&actions.parentElement;if(!box)return;var wrap=document.createElement("div");wrap.style.marginTop="10px";wrap.innerHTML='<button class="btn secondary small" id="optimizePhotoStorageBtn" type="button">Speicher optimieren</button><div class="muted" id="photoStorageStatus" style="margin-top:7px"></div>';box.appendChild(wrap);btn=document.getElementById("optimizePhotoStorageBtn");if(btn&&!btn.dataset.storageBound){btn.dataset.storageBound="1";btn.addEventListener("click",optimize)}updateStatus()}
function updateStatus(){var s=document.getElementById("photoStorageStatus");if(!s)return;var st=window.state||{},cloud=0;["plants","habitats","animals"].forEach(function(k){(st[k]||[]).forEach(function(it){if(it.photoRef)cloud++})});var local=inlineCount();s.textContent=(configured(cfg())?"Kostenloser Supabase-Fotospeicher bereit":"Geräte-Sync nötig für Cloud-Fotos")+" · Cloud: "+cloud+" · noch lokal: "+local.count}
function installErrorAction(){var e=document.getElementById("globalError");if(!e||e.dataset.photoStorageReady)return;e.dataset.photoStorageReady="1";var obs=new MutationObserver(function(){if(e.textContent.indexOf("Lokaler Speicher ist voll")>=0&&!e.querySelector(".photo-storage-cta")){var b=document.createElement("button");b.type="button";b.className="btn small photo-storage-cta";b.style.marginTop="10px";b.textContent="Speicher jetzt optimieren";b.onclick=optimize;e.appendChild(document.createElement("br"));e.appendChild(b)}});obs.observe(e,{childList:true,subtree:true,characterData:true});if(e.textContent.indexOf("Lokaler Speicher ist voll")>=0)obs.takeRecords()}
function bindDeletes(){[["deletePlantBtn","plants","editPlantId"],["deleteHabitatBtn","habitats","editHabitatId"],["deleteAnimalBtn","animals","editAnimalId"]].forEach(function(x){var b=document.getElementById(x[0]);if(!b)return;b.addEventListener("click",function(){var st=window.state||{},id=st[x[2]],it=(st[x[1]]||[]).find(function(v){return String(v.id)===String(id)}),ref=it&&it.photoRef;if(!ref)return;setTimeout(function(){var exists=(st[x[1]]||[]).some(function(v){return String(v.id)===String(id)});if(!exists)api("delete",{ref:ref}).catch(function(){})},250)},true)})}
function init(){Object.keys(specs).forEach(bindType);installSettings();installErrorAction();bindDeletes();refreshSigned();setTimeout(updateStatus,800)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
window.JGWPhotoStorage={optimize:optimize,refresh:refreshSigned};
})();
