(function(){
"use strict";
var STORE="giess_check_garten_v3";
var SYNC_STORE="johannas_gartenwelt_sync_v1";
var ITERATIONS=310000;
var lastSetupLink="";
var activeToken="";
var receiverContext="standalone";
var SETUP_COOKIE="jgw_setup_install";
function el(id){return document.getElementById(id)}
function show(id,on){var n=el(id);if(n)n.classList.toggle("hidden",!on)}
function hideAll(){show("generatorBox",false);show("installBox",false);show("receiverBox",false)}
function readJSON(key){try{return JSON.parse(localStorage.getItem(key)||"null")||{}}catch(e){return{}}}
function setupCookiePath(){var p=location.pathname||"/";return p.slice(0,p.lastIndexOf("/")+1)||"/"}
function setInstallCookie(token){if(!token)return;document.cookie=SETUP_COOKIE+"="+encodeURIComponent(token)+"; Max-Age=1800; Path="+setupCookiePath()+"; Secure; SameSite=Strict"}
function getInstallCookie(){var parts=(document.cookie||"").split(";");for(var i=0;i<parts.length;i++){var x=parts[i].trim(),prefix=SETUP_COOKIE+"=";if(x.indexOf(prefix)===0){try{return decodeURIComponent(x.slice(prefix.length))}catch(e){return x.slice(prefix.length)}}}return""}
function clearInstallCookie(){document.cookie=SETUP_COOKIE+"=; Max-Age=0; Path="+setupCookiePath()+"; Secure; SameSite=Strict"}
function hasValidStoredConfig(){var c=currentConfig();return validUrl(c.url)&&c.key.length>10&&c.gardenId.length>=6&&(/^[a-f0-9]{64}$/i.test(c.secretHash)||c.legacyPin.length>=6)}
function isStandalone(){return !!(window.matchMedia&&window.matchMedia("(display-mode: standalone)").matches)||window.navigator.standalone===true}
function b64url(bytes){var s="";bytes=new Uint8Array(bytes);for(var i=0;i<bytes.length;i++)s+=String.fromCharCode(bytes[i]);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function fromB64url(s){s=String(s||"").replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";var raw=atob(s),a=new Uint8Array(raw.length);for(var i=0;i<raw.length;i++)a[i]=raw.charCodeAt(i);return a}
function textToB64url(s){return b64url(new TextEncoder().encode(s))}
function b64urlToText(s){return new TextDecoder().decode(fromB64url(s))}
async function sha256Hex(s){var b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return Array.from(new Uint8Array(b)).map(function(x){return x.toString(16).padStart(2,"0")}).join("")}
async function deriveKey(pin,salt,iterations){if(!window.crypto||!crypto.subtle)throw new Error("Verschlüsselung wird von diesem Browser nicht unterstützt.");var base=await crypto.subtle.importKey("raw",new TextEncoder().encode(pin),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt:salt,iterations:iterations,hash:"SHA-256"},base,{name:"AES-GCM",length:256},false,["encrypt","decrypt"])}
async function encryptPayload(payload,pin){var salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await deriveKey(pin,salt,ITERATIONS),plain=new TextEncoder().encode(JSON.stringify(payload)),cipher=await crypto.subtle.encrypt({name:"AES-GCM",iv:iv},key,plain);return{v:1,k:"PBKDF2-SHA256",i:ITERATIONS,s:b64url(salt),n:b64url(iv),c:b64url(cipher)}}
async function decryptEnvelope(envelope,pin){if(!envelope||envelope.v!==1||!envelope.s||!envelope.n||!envelope.c)throw new Error("Ungültiger Einrichtungs-Code.");var salt=fromB64url(envelope.s),iv=fromB64url(envelope.n),cipher=fromB64url(envelope.c),key=await deriveKey(pin,salt,Number(envelope.i)||ITERATIONS);var plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:iv},key,cipher);return JSON.parse(new TextDecoder().decode(plain))}
function currentConfig(){var app=readJSON(STORE),sync=readJSON(SYNC_STORE);return{app:app,sync:sync,url:String(sync.url||"").trim().replace(/\/+$/,""),key:String(sync.key||"").trim(),gardenId:String(sync.gardenId||"").trim().toLowerCase(),secretHash:String(sync.secretHash||"").trim().toLowerCase(),legacyPin:String(sync.pin||""),plantnetKey:String(app.settings&&app.settings.plantnetKey||"").trim()}}
function validUrl(v){return /^https:\/\/[^/]+\.supabase\.co$/i.test(v)}
function renderChecks(){var c=currentConfig(),credential=/^[a-f0-9]{64}$/i.test(c.secretHash)||c.legacyPin.length>=6,checks=[{name:"Supabase Project URL",ok:validUrl(c.url),info:c.url||"fehlt"},{name:"Supabase Publishable Key",ok:c.key.length>10,info:c.key?"gespeichert":"fehlt"},{name:"Garten-ID",ok:c.gardenId.length>=6,info:c.gardenId?c.gardenId.toUpperCase():"fehlt"},{name:"PlantNet API-Key",ok:c.plantnetKey.length>5,info:c.plantnetKey?"gespeichert":"fehlt"},{name:"abgeleiteter Zugriffsschlüssel",ok:credential,info:credential?"gespeichert · die PIN selbst bleibt ungespeichert":"fehlt"}],all=checks.every(function(x){return x.ok});el("configChecks").className="status "+(all?"ok":"bad");el("configChecks").innerHTML=checks.map(function(x){return '<div class="check"><span class="dot '+(x.ok?'ok':'bad')+'"></span><div><b>'+x.name+'</b><br><span class="muted">'+String(x.info).replace(/[&<>]/g,function(ch){return{"&":"&amp;","<":"&lt;",">":"&gt;"}[ch]})+'</span></div></div>'}).join("");el("makeQr").disabled=!all;return all}
async function makeQr(){if(!renderChecks())return;var c=currentConfig(),pin=String(el("generatorPin").value||""),payload={v:1,created:new Date().toISOString(),supabaseUrl:c.url,supabaseKey:c.key,gardenId:c.gardenId,plantnetKey:c.plantnetKey};if(pin.length<6){alert("Bitte die Garten-PIN mit mindestens 6 Zeichen eingeben.");return}el("makeQr").disabled=true;el("makeQr").textContent="QR-Code wird verschlüsselt …";try{var entered=await sha256Hex(c.gardenId+"|"+pin),expected=c.secretHash;if(!/^[a-f0-9]{64}$/i.test(expected)&&c.legacyPin.length>=6)expected=await sha256Hex(c.gardenId+"|"+c.legacyPin);if(!expected||entered!==expected)throw new Error("Die eingegebene Garten-PIN stimmt nicht.");var sync=c.sync;sync.secretHash=entered;delete sync.pin;localStorage.setItem(SYNC_STORE,JSON.stringify(sync));var envelope=await encryptPayload(payload,pin),token=textToB64url(JSON.stringify(envelope)),base=location.origin+location.pathname;lastSetupLink=base+"#setup="+token;el("setupLink").textContent=lastSetupLink;if(typeof QRCode==="undefined")throw new Error("QR-Bibliothek konnte nicht geladen werden.");el("qrCanvas").innerHTML="";new QRCode(el("qrCanvas"),{text:lastSetupLink,width:320,height:320,correctLevel:QRCode.CorrectLevel.M});show("qrResult",true);el("qrResult").scrollIntoView({behavior:"smooth",block:"start"})}catch(e){alert("QR-Code konnte nicht erzeugt werden: "+e.message)}finally{el("generatorPin").value="";el("makeQr").disabled=false;el("makeQr").textContent="Zugangs-QR-Code erzeugen"}}
async function copyLink(){if(!lastSetupLink)return;try{await navigator.clipboard.writeText(lastSetupLink);el("copyLink").textContent="Kopiert";setTimeout(function(){el("copyLink").textContent="Einrichtungslink kopieren"},1600)}catch(e){prompt("Einrichtungslink kopieren:",lastSetupLink)}}
function tokenFromHash(){var h=location.hash||"",m=h.match(/^#setup=([A-Za-z0-9_-]+)$/);return m?m[1]:""}
function tokenFromInstallQuery(){try{return new URLSearchParams(location.search).get("install")||""}catch(e){return""}}
function putTokenInInstallUrl(token){var url=location.pathname+"?install="+encodeURIComponent(token);history.replaceState(null,"",url)}
function clearSetupUrl(){history.replaceState(null,"",location.pathname)}
function showInstallGuide(token){activeToken=token;setInstallCookie(token);putTokenInInstallUrl(token);hideAll();show("installBox",true)}
function showReceiver(token,context){activeToken=token;receiverContext=context||"standalone";hideAll();show("receiverBox",true);el("receiverMode").textContent=receiverContext==="safari"?"Safari":"Home-Screen-App";show("standaloneConfirmed",receiverContext!=="safari");el("receiverIntro").innerHTML=receiverContext==="safari"?"Du bist noch in Safari. Bitte nicht hier einrichten, sondern zuerst als Web-App zum Home-Bildschirm hinzufügen und anschließend das neue Home-Screen-Symbol öffnen.":"Der Einrichtungs-Code wurde in die Home-Screen-App übernommen. Gib die Garten-PIN einmal ein; gespeichert wird anschließend nur der daraus abgeleitete abgeleiteter Zugriffsschlüssel.";setTimeout(function(){try{el("setupPin").focus()}catch(e){}},80)}
function storeConfig(p,secretHash){var app=readJSON(STORE);app.settings=app.settings||{};app.settings.plantnetKey=String(p.plantnetKey||"");if(!Array.isArray(app.plants))app.plants=[];if(!Array.isArray(app.zones))app.zones=[];localStorage.setItem(STORE,JSON.stringify(app));var sync={url:String(p.supabaseUrl).replace(/\/+$/,""),key:String(p.supabaseKey),gardenId:String(p.gardenId).trim().toLowerCase(),secretHash:String(secretHash||"").toLowerCase(),enabled:true,revision:0,lastSync:"",lastPayloadHash:"",dirty:false,initialPull:true};localStorage.setItem(SYNC_STORE,JSON.stringify(sync))}
async function unlockSetup(e){e.preventDefault();var pin=el("setupPin").value;if(pin.length<6){el("receiverStatus").className="status bad";el("receiverStatus").textContent="Bitte die Garten-PIN mit mindestens 6 Zeichen eingeben.";return}if(!activeToken){el("receiverStatus").className="status bad";el("receiverStatus").textContent="Einrichtungs-Code fehlt.";return}el("unlockBtn").disabled=true;el("receiverStatus").className="status warn";el("receiverStatus").textContent="Zugangsdaten werden entschlüsselt …";try{var envelope=JSON.parse(b64urlToText(activeToken)),p=await decryptEnvelope(envelope,pin);if(!p||p.v!==1||!validUrl(String(p.supabaseUrl||""))||String(p.supabaseKey||"").length<=10||String(p.gardenId||"").length<6)throw new Error("Der QR-Code enthält keine gültige Garten-Konfiguration.");var secretHash=await sha256Hex(String(p.gardenId).trim().toLowerCase()+"|"+pin);storeConfig(p,secretHash);el("setupPin").value="";clearInstallCookie();clearSetupUrl();el("receiverStatus").className="status ok";el("receiverStatus").innerHTML="<b>Einrichtung abgeschlossen.</b><br>Garten-ID, Supabase-Zugang und PlantNet-Key sind gespeichert. Die PIN wurde verworfen; lokal bleibt nur der abgeleitete abgeleiteter Zugriffsschlüssel. Der gemeinsame Garten wird geladen.";setTimeout(function(){location.replace("./")},1000)}catch(err){console.warn(err);el("receiverStatus").className="status bad";el("receiverStatus").textContent="PIN falsch oder QR-Code beschädigt. Bitte erneut versuchen.";el("unlockBtn").disabled=false}}
function cancelSetup(){clearSetupUrl();location.replace("./")}
function cancelInstall(){clearSetupUrl();location.replace("./")}
function safariOnly(){showReceiver(activeToken,"safari")}
function init(){var installToken=tokenFromInstallQuery(),hashToken=tokenFromHash(),standalone=isStandalone(),cookieToken=getInstallCookie();hideAll();
if(standalone){
  if(installToken&&installToken!=="1")showReceiver(installToken,"standalone");
  else if(hashToken)showReceiver(hashToken,"standalone");
  else if(cookieToken)showReceiver(cookieToken,"standalone");
  else if(hasValidStoredConfig()){location.replace("./");return}
  else{show("receiverBox",true);el("standaloneConfirmed").className="status warn";el("standaloneConfirmed").innerHTML="<b>Web-App-Modus erkannt.</b><br>Die Einrichtungsdaten wurden aber nicht übernommen.";el("receiverIntro").innerHTML="Bitte dieses Symbol wieder entfernen und die Einrichtung erneut über den QR-Code starten. Beim Hinzufügen muss <b>Als Web-App öffnen</b> aktiv sein.";el("unlockForm").classList.add("hidden");el("receiverStatus").className="status bad";el("receiverStatus").textContent="Einrichtungsdaten fehlen."}
}else if(installToken&&installToken!=="1")showInstallGuide(installToken);
else if(hashToken)showInstallGuide(hashToken);
else{show("generatorBox",true);renderChecks()}
el("makeQr").addEventListener("click",makeQr);el("copyLink").addEventListener("click",copyLink);el("unlockForm").addEventListener("submit",unlockSetup);el("cancelSetup").addEventListener("click",cancelSetup);el("cancelInstall").addEventListener("click",cancelInstall);el("safariOnly").addEventListener("click",safariOnly)}
init();
})();
