from pathlib import Path
p=Path('setup.html')
s=p.read_text(encoding='utf-8')
s=s.replace('Auf dem neuen iPhone oder iPad mit der Kamera scannen. <b>Wichtig:</b> Öffnet sich danach eine Vorschau mit einem Kompass-Symbol unten rechts, zuerst auf den Kompass tippen und die Seite im echten Safari öffnen. Erst dort zum Home-Bildschirm hinzufügen.','Auf dem neuen iPhone oder iPad mit der Kamera scannen. Wenn oben links <b>„&lt; Kamera“</b> steht und unten die Safari-Leiste mit <b>…</b> sichtbar ist, bist du bereits im echten Safari. Tippe dort unten rechts auf <b>…</b>, dann auf <b>Teilen</b> und anschließend auf <b>Zu Home-Bildschirm hinzufügen</b>.')
s=s.replace('<div class="installhero"><b>Wichtig:</b> Wenn unten rechts ein <b>Kompass-Symbol</b> sichtbar ist, bist du noch in der QR-/In-App-Vorschau. <b>Zuerst auf den Kompass tippen und in Safari öffnen.</b> Erst dort die Seite zum Home-Bildschirm hinzufügen und <b>„Als Web-App öffnen“ eingeschaltet lassen</b>. Danach ausschließlich das neue Gartenwelt-Symbol auf dem Home-Bildschirm öffnen.</div>','<div class="installhero"><b>Wichtig:</b> Auf iOS 26 bedeutet <b>„&lt; Kamera“ oben links</b> zusammen mit der unteren Leiste bereits: Du bist in Safari. Unten rechts auf <b>…</b> tippen, dann <b>Teilen</b> → <b>Zu Home-Bildschirm hinzufügen</b>. Im nächsten Bildschirm <b>„Als Web-App öffnen“ eingeschaltet lassen</b>. Danach ausschließlich das neue Gartenwelt-Symbol auf dem Home-Bildschirm öffnen.</div>')
s=s.replace('<div class="step"><div class="stepno">1</div><div class="steptext">Nach dem QR-Scan: Ist unten rechts ein <b>Kompass-Symbol</b> sichtbar, darauf tippen. Dadurch öffnet sich die Seite im echten Safari.</div></div>\n      <div class="step"><div class="stepno">2</div><div class="steptext">Erst jetzt in Safari auf <b>Teilen</b> tippen.</div></div>\n      <div class="step"><div class="stepno">3</div><div class="steptext"><b>Zum Home-Bildschirm</b> auswählen.</div></div>\n      <div class="step"><div class="stepno">4</div><div class="steptext"><b>Als Web-App öffnen</b> eingeschaltet lassen.</div></div>\n      <div class="step"><div class="stepno">5</div><div class="steptext"><b>Hinzufügen</b> bestätigen.</div></div>\n      <div class="step"><div class="stepno">6</div><div class="steptext">Safari verlassen und das neue Symbol <b>Johanna´s Gartenwelt</b> auf dem Home-Bildschirm öffnen.</div></div>\n      <div class="step"><div class="stepno">7</div><div class="steptext">Dort einmal die <b>Garten-PIN</b> eingeben. Danach sind Garten, Sync und PlantNet dauerhaft in der Home-Screen-App eingerichtet.</div></div>','<div class="step"><div class="stepno">1</div><div class="steptext">Nach dem QR-Scan zeigt iOS ggf. oben links <b>„&lt; Kamera“</b>. Das ist in Ordnung – du bist bereits in Safari.</div></div>\n      <div class="step"><div class="stepno">2</div><div class="steptext">Unten rechts auf <b>…</b> tippen und danach <b>Teilen</b> wählen.</div></div>\n      <div class="step"><div class="stepno">3</div><div class="steptext"><b>Zu Home-Bildschirm hinzufügen</b> auswählen.</div></div>\n      <div class="step"><div class="stepno">4</div><div class="steptext"><b>Als Web-App öffnen</b> eingeschaltet lassen.</div></div>\n      <div class="step"><div class="stepno">5</div><div class="steptext"><b>Hinzufügen</b> bestätigen.</div></div>\n      <div class="step"><div class="stepno">6</div><div class="steptext">Safari verlassen und das neue Symbol <b>Johanna´s Gartenwelt</b> auf dem Home-Bildschirm öffnen. Jetzt dürfen keine Safari-Leisten mehr sichtbar sein.</div></div>\n      <div class="step"><div class="stepno">7</div><div class="steptext">Dort einmal die <b>Garten-PIN</b> eingeben. Danach sind Garten, Sync und PlantNet dauerhaft in der Home-Screen-App eingerichtet.</div></div>')
if 'Kompass-Symbol' in s:
    raise SystemExit('old compass wording still present')
if '&lt; Kamera' not in s or 'Zu Home-Bildschirm hinzufügen' not in s:
    raise SystemExit('new wording missing')
p.write_text(s,encoding='utf-8')
print('patched')
