from pathlib import Path
import re

p=Path('index.html')
s=p.read_text(encoding='utf-8')
orig=s

def rep(old,new,label):
    global s
    if old not in s:
        raise SystemExit(f'missing marker: {label}')
    s=s.replace(old,new,1)

def sub(pattern,repl,label,flags=0):
    global s
    s2,n=re.subn(pattern,repl,s,count=1,flags=flags)
    if n!=1:
        raise SystemExit(f'{label}: expected 1 replacement, got {n}')
    s=s2

if 'id="natureTabs"' in s:
    raise SystemExit('Naturgarten upgrade already present')

# ---------- CSS ----------
css=r'''
/* JGW NATURGARTEN */
.btn{background:linear-gradient(135deg,#3f6844,#648766);color:#fff}
.btn.danger{background:linear-gradient(135deg,#914747,#aa5a5a);color:#fff}
.sync-conflict .btn:not(.danger){background:#3f6844!important;color:#fff!important;border-color:#315538!important}
.sync-conflict .btn.danger{background:#914747!important;color:#fff!important;border-color:#793838!important}
.nature-head{overflow:hidden}.nature-tabs{display:flex;gap:7px;overflow:auto;margin-top:13px;padding-bottom:2px;scrollbar-width:none}.nature-tabs::-webkit-scrollbar{display:none}.nature-tab{border:1px solid #e2d4c5;background:#fffdf9;color:var(--forest-dark);border-radius:999px;padding:9px 13px;font-weight:800;white-space:nowrap}.nature-tab.active{background:linear-gradient(135deg,var(--forest),var(--sage));color:#fff;border-color:transparent}.nature-count{display:inline-grid;place-items:center;min-width:19px;height:19px;padding:0 5px;margin-left:4px;border-radius:999px;background:rgba(255,255,255,.68);font-size:10px;color:inherit}.nature-pane.hidden{display:none!important}
.library-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:14px}.nature-card{position:relative;background:#fffdf9;border:1px solid var(--line);border-radius:20px;overflow:hidden;box-shadow:0 9px 20px rgba(80,100,72,.09);min-width:0}.nature-card-main{display:block;width:100%;border:0;background:transparent;text-align:left;color:inherit;padding:0}.nature-card-photo{aspect-ratio:4/3;background:linear-gradient(145deg,#eef4e9,#f7efe5);display:grid;place-items:center;font-size:46px;overflow:hidden;position:relative}.nature-card-photo img{width:100%;height:100%;object-fit:cover}.nature-card-body{padding:11px 12px 13px}.nature-card-name{font-family:Georgia,"Times New Roman",serif;color:var(--forest-dark);font-size:17px;font-weight:700;line-height:1.15}.nature-card-sub{font-size:10px;color:var(--muted);margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.nature-card-meta{display:flex;gap:5px;flex-wrap:wrap;margin-top:8px}.nature-chip{font-size:9px;font-weight:800;padding:4px 7px;border-radius:999px;background:#f5eee5;color:#6b6055;border:1px solid #eadfd2}.nature-chip.good{background:#eaf4e5;color:#49663f;border-color:#cbdcc1}.nature-chip.plan{background:#fff4d9;color:#76612c;border-color:#ead9a9}.nature-impact{position:absolute;right:8px;top:8px;z-index:3;border-radius:999px;padding:5px 8px;background:rgba(255,253,249,.95);border:1px solid rgba(200,165,106,.48);font-size:10px;font-weight:900;color:#5d603b;box-shadow:0 3px 10px rgba(54,49,44,.11)}
.library-toolbar{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}.library-search{min-width:220px;max-width:360px;width:100%;border:1px solid #ddcfc0;border-radius:12px;padding:10px 12px;background:#fffdf9;color:var(--txt)}.library-filters{display:flex;gap:6px;overflow:auto;margin-top:10px;scrollbar-width:none}.library-filters::-webkit-scrollbar{display:none}.library-filter{border:1px solid #e5d8ca;background:#fffdf9;color:var(--muted);padding:7px 10px;border-radius:999px;white-space:nowrap;font-size:11px;font-weight:800}.library-filter.active{background:var(--forest);color:#fff;border-color:var(--forest)}
.tax-search-field{position:relative}.tax-results{position:absolute;left:0;right:0;top:calc(100% - 1px);z-index:1500;background:#fffdf9;border:1px solid var(--line);border-radius:13px;box-shadow:0 12px 28px rgba(54,49,44,.18);overflow:auto;max-height:320px}.tax-result{width:100%;border:0;border-bottom:1px solid #f0e7dd;background:#fffdf9;padding:9px 10px;text-align:left;color:var(--txt);display:grid;grid-template-columns:46px minmax(0,1fr);gap:9px;align-items:center}.tax-result:last-child{border-bottom:0}.tax-result:hover,.tax-result:focus{background:var(--ok);outline:none}.tax-thumb{width:46px;height:46px;border-radius:10px;overflow:hidden;background:#eef3e9;display:grid;place-items:center;font-size:23px}.tax-thumb img{width:100%;height:100%;object-fit:cover}.tax-result b{display:block;color:var(--forest-dark);font-size:13px}.tax-result small{display:block;color:var(--muted);font-size:10px;margin-top:2px;line-height:1.3}
.reference-note{font-size:9px;color:var(--muted);line-height:1.3;margin-top:5px}.species-count{position:absolute;left:8px;bottom:8px;background:rgba(63,95,67,.9);color:#fff;border-radius:999px;padding:5px 8px;font-size:10px;font-weight:900}.observation-list{display:grid;gap:7px;margin-top:9px}.observation-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:center;background:#f8f2e9;border-radius:11px;padding:9px}.observation-row b{display:block;color:#5d5349;font-size:12px}.observation-row small{display:block;color:var(--muted);font-size:10px;margin-top:2px}
.native-auto{margin-top:10px;padding:11px 12px;border-radius:13px;background:linear-gradient(135deg,#eef5e8,#f8f3e7);border:1px solid #d9e3cb;font-size:12px;line-height:1.45}.practice-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:10px}.practice-item{display:flex;gap:8px;align-items:flex-start;border:1px solid #e5d9cb;background:#fffdf9;border-radius:12px;padding:9px;font-size:12px;line-height:1.35}.practice-item input{margin-top:2px;width:18px;height:18px;flex:0 0 auto}.score-breakdown{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:6px;margin-top:10px}.score-part{padding:8px;border-radius:11px;background:#f8f2e9;text-align:center}.score-part b{display:block;color:var(--forest-dark);font-size:14px}.score-part small{font-size:9px;color:var(--muted)}
.map-nature-marker{width:28px;height:28px;border-radius:50%;display:grid;place-items:center;background:#fffdf9;border:2px solid #806c51;box-shadow:0 2px 8px rgba(0,0,0,.24);font-size:14px}.map-animal-marker{border-color:#7a5e82;background:#fff7fb}
@media(max-width:760px){.library-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.nature-card-name{font-size:15px}.nature-card-body{padding:9px 9px 11px}.practice-grid{grid-template-columns:1fr}.score-breakdown{grid-template-columns:repeat(2,minmax(0,1fr))}.library-search{min-width:0}.nature-tabs{margin-left:-2px;margin-right:-2px}}
@media(max-width:350px){.library-grid{grid-template-columns:1fr}}
/* /JGW NATURGARTEN */
'''
rep('/* /JGW FINAL DESIGN */',css+'\n/* /JGW FINAL DESIGN */','css insertion')

# ---------- NAV + NATURGARTEN HTML ----------
rep('<span>Pflanzen</span>','<span>Naturgarten</span>','nav label')
rep('Dein gespeicherter Gartenausschnitt mit Pflanzen und Standortzonen.','Dein gespeicherter Gartenausschnitt mit Pflanzen, Lebensräumen, Tierbeobachtungen und Standortzonen.','map subtitle')

m=re.search(r'<section class="view" id="view-plants">(.*?)</section>\n\n<section class="view" id="view-calendar">',s,re.S)
if not m:
    raise SystemExit('plant view not found')
old_inner=m.group(1)
nature_header=r'''
  <div class="box nature-head">
    <div class="topline"><div><h2>Naturgarten-Sammlung</h2><div class="muted">Pflanzen, Lebensräume und beobachtete Tiere gemeinsam im Blick.</div></div></div>
    <div class="nature-tabs" id="natureTabs" role="tablist" aria-label="Naturgarten-Sammlung">
      <button class="nature-tab active" data-nature="plants" type="button">🌿 Pflanzen <span class="nature-count" id="naturePlantCount">0</span></button>
      <button class="nature-tab" data-nature="habitats" type="button">🪵 Lebensräume <span class="nature-count" id="natureHabitatCount">0</span></button>
      <button class="nature-tab" data-nature="animals" type="button">🦋 Tiere <span class="nature-count" id="natureAnimalCount">0</span></button>
    </div>
  </div>
  <div class="nature-pane" id="naturePlantsPane">'''
habitats_animals=r'''
  </div>
  <div class="nature-pane hidden" id="natureHabitatsPane">
    <div class="box">
      <div class="library-toolbar"><div><h2>Lebensräume</h2><div class="muted">Wasser, Totholz, Bodenstellen und weitere Naturgarten-Strukturen als eigene Karten.</div></div><div class="actions"><input class="library-search" id="habitatSearch" type="search" placeholder="Lebensraum oder Bereich suchen"><button class="btn" id="newHabitatBtn" type="button">+ Lebensraum</button></div></div>
      <div class="library-filters" id="habitatFilters"></div>
    </div>
    <div class="box hidden" id="habitatEditor">
      <div class="topline"><h3 id="habitatEditorTitle">Lebensraum hinzufügen</h3><button class="btn ghost small" id="closeHabitatEditor" type="button">Schließen</button></div>
      <form id="habitatForm"><input type="hidden" id="habitatId">
        <div class="formgrid">
          <div class="field"><label for="habitatType">Lebensraum *</label><select id="habitatType" required></select></div>
          <div class="field"><label for="habitatStatus">Status</label><select id="habitatStatus"><option value="idea">Idee</option><option value="planned">Geplant</option><option value="present" selected>Vorhanden</option><option value="optimized">Optimiert</option></select></div>
          <div class="field"><label for="habitatArea">Gartenbereich</label><input id="habitatArea" placeholder="z. B. hinteres Beet"></div>
          <div class="field"><label for="habitatPhoto">Foto</label><input id="habitatPhoto" type="file" accept="image/*" capture="environment"></div>
          <div class="field full"><div class="photo-preview" id="habitatPhotoPreview">Foto</div></div>
          <div class="field full"><label for="habitatNotes">Notizen</label><textarea id="habitatNotes" placeholder="Was ist hier besonders? Was möchtest du noch verbessern?"></textarea></div>
        </div>
        <div class="eco-form-preview" id="habitatImpactPreview"></div>
        <div class="actions" style="margin-top:14px"><button class="btn" type="submit">Speichern</button><button class="btn secondary" id="saveHabitatAndPlaceBtn" type="button">Speichern & auf Karte setzen</button></div>
      </form>
    </div>
    <div class="library-grid" id="habitatList"></div>
  </div>
  <div class="nature-pane hidden" id="natureAnimalsPane">
    <div class="box">
      <div class="library-toolbar"><div><h2>Tierbeobachtungen</h2><div class="muted">Tiere im Garten festhalten. Die kostenlose iNaturalist-Suche hilft beim Finden des richtigen Namens – ohne automatische Bilderkennung.</div></div><div class="actions"><input class="library-search" id="animalCollectionSearch" type="search" placeholder="Tier, Art oder Bereich suchen"><button class="btn" id="newAnimalBtn" type="button">+ Beobachtung</button></div></div>
    </div>
    <div class="box hidden" id="animalEditor">
      <div class="topline"><h3 id="animalEditorTitle">Tier beobachten</h3><button class="btn ghost small" id="closeAnimalEditor" type="button">Schließen</button></div>
      <form id="animalForm">
        <input type="hidden" id="animalId"><input type="hidden" id="animalTaxonId"><input type="hidden" id="animalScientific"><input type="hidden" id="animalRefPhoto"><input type="hidden" id="animalRefAttribution">
        <div class="formgrid">
          <div class="field full tax-search-field"><label for="animalName">Tiername *</label><input id="animalName" required autocomplete="off" placeholder="z. B. Tagpfauenauge"><div class="plant-name-assist muted" id="animalTaxonAssist">Ab 3 Zeichen durchsucht die Gartenwelt kostenlos iNaturalist.</div><div class="tax-results hidden" id="animalTaxonResults" role="listbox" aria-label="Tiervorschläge"></div></div>
          <div class="field"><label for="animalGroup">Tiergruppe</label><select id="animalGroup"><option value="insect">Insekt</option><option value="butterfly">Schmetterling / Nachtfalter</option><option value="bee">Biene / Hummel / Wespe</option><option value="beetle">Käfer</option><option value="spider">Spinne</option><option value="bird">Vogel</option><option value="mammal">Säugetier</option><option value="amphibian">Amphibie</option><option value="reptile">Reptil</option><option value="mollusc">Schnecke / Weichtier</option><option value="other">Andere</option></select></div>
          <div class="field"><label for="animalDate">Beobachtet am</label><input id="animalDate" type="date"></div>
          <div class="field"><label for="animalArea">Gartenbereich</label><input id="animalArea" placeholder="z. B. Wildbeet"></div>
          <div class="field"><label for="animalPhoto">Eigenes Foto</label><input id="animalPhoto" type="file" accept="image/*" capture="environment"></div>
          <div class="field full"><div class="photo-preview" id="animalPhotoPreview">Foto optional</div><div class="reference-note" id="animalReferenceNote"></div></div>
          <div class="field"><label for="animalLinkedPlant">Beobachtet an Pflanze</label><select id="animalLinkedPlant"><option value="">– keine / unbekannt –</option></select></div>
          <div class="field"><label for="animalLinkedHabitat">Beobachtet am Lebensraum</label><select id="animalLinkedHabitat"><option value="">– keiner / unbekannt –</option></select></div>
          <div class="field full"><label for="animalNotes">Notizen</label><textarea id="animalNotes" placeholder="z. B. mehrere Tiere, Verhalten, Besonderheiten …"></textarea></div>
        </div>
        <div class="actions" style="margin-top:14px"><button class="btn" type="submit">Beobachtung speichern</button><button class="btn secondary" id="saveAnimalAndPlaceBtn" type="button">Speichern & auf Karte setzen</button></div>
      </form>
    </div>
    <div class="library-grid" id="animalList"></div>
  </div>
'''
new_inner=nature_header+old_inner+habitats_animals
s=s[:m.start()]+ '<section class="view" id="view-plants">'+new_inner+'</section>\n\n<section class="view" id="view-calendar">'+s[m.end():]

# ---------- SETTINGS: practice instead of duplicate habitat checkboxes ----------
new_settings=r'''<section class="settings-section" id="settingsEcology">
      <h3>Naturnahe Praxis</h3>
      <div class="muted">Konkrete Lebensräume werden jetzt in der Naturgarten-Sammlung als Foto-Karten gepflegt. Hier stehen nur übergreifende Gartenprinzipien.</div>
      <div class="practice-grid">
        <label class="practice-item"><input type="checkbox" data-practice="noPesticides"><span><b>Ohne Insektizide</b><br><span class="muted">Keine bienen- oder insektengefährdenden Spritzmittel.</span></span></label>
        <label class="practice-item"><input type="checkbox" data-practice="leaveStemsInWinter"><span><b>Stängel über Winter stehen lassen</b><br><span class="muted">Ein Teil der Stauden bleibt als Winterquartier erhalten.</span></span></label>
        <label class="practice-item"><input type="checkbox" data-practice="leavesPartlyRemain"><span><b>Laub teilweise liegen lassen</b><br><span class="muted">Nicht jede Ecke wird im Herbst vollständig aufgeräumt.</span></span></label>
        <label class="practice-item"><input type="checkbox" data-practice="peatFree"><span><b>Torffrei gärtnern</b><br><span class="muted">Substrate möglichst ohne Torf verwenden.</span></span></label>
        <label class="practice-item"><input type="checkbox" data-practice="lessFrequentMowing"><span><b>Seltener / abschnittsweise mähen</b><br><span class="muted">Blüh- und Rückzugsflächen bleiben zeitweise stehen.</span></span></label>
        <label class="practice-item"><input type="checkbox" data-practice="reducedNightLight"><span><b>Wenig Licht in der Nacht</b><br><span class="muted">Außenlicht gezielt und möglichst kurz einsetzen – auch für Nachtfalter.</span></span></label>
      </div>
      <div class="native-auto" id="nativePlantAutoStatus"><b>Heimische Pflanzen:</b> Wird automatisch aus den erfassten Arten abgeleitet.</div>
      <div class="habitat-score" id="practiceScoreText"></div>
    </section>'''
sub(r'<section class="settings-section" id="settingsEcology">.*?</section>',new_settings,'settings ecology',re.S)
rep('Pflanzenerkennung und Namenssuche optional Pl@ntNet.','Pflanzenerkennung und Namenssuche optional Pl@ntNet · Tier-Namenssuche iNaturalist (kostenlos, ohne API-Key).','sources')

# ---------- STATE + ECOLOGY MODEL ----------
rep('var DEFAULT_HABITAT={waterSource:false,deadwood:false,bareSoil:false,wildCorner:false,noPesticides:true,nativePlantsFocus:false};',r'''var DEFAULT_HABITAT={waterSource:false,deadwood:false,bareSoil:false,wildCorner:false,noPesticides:true,nativePlantsFocus:false};
var DEFAULT_PRACTICE={noPesticides:true,leaveStemsInWinter:false,leavesPartlyRemain:false,peatFree:false,lessFrequentMowing:false,reducedNightLight:false};
var HABITAT_LIBRARY={
 water_station:{title:"Wasserstelle",category:"water",icon:"💧",score:8,supports:["wildbienen","schmetterlinge","schwebfliegen"],tip:"Flach, sauber und mit sicheren Landeplätzen anbieten."},
 mini_pond:{title:"Miniteich / Teich",category:"water",icon:"🪷",score:10,supports:["libellen","wildbienen","andere insekten"],tip:"Flache Randzonen und heimische Wasserpflanzen erhöhen den Wert."},
 deadwood:{title:"Totholz",category:"structure",icon:"🪵",score:8,supports:["wildbienen","käfer","andere insekten"],tip:"Unbehandeltes Holz möglichst dauerhaft und teilweise sonnig belassen."},
 stems:{title:"Markhaltige Stängel",category:"structure",icon:"🌾",score:7,supports:["wildbienen"],tip:"Abgeschnittene Stängel senkrecht oder schräg und trocken stehen lassen."},
 bare_soil:{title:"Offene Bodenstelle",category:"structure",icon:"🟤",score:9,supports:["wildbienen"],tip:"Nicht mulchen und möglichst sonnig, trocken sowie ungestört lassen."},
 sandarium:{title:"Sandarium / Sandlinse",category:"structure",icon:"🏖️",score:10,supports:["wildbienen"],tip:"Ungewaschenen Sand mit bindigen Anteilen verwenden und sonnig anlegen."},
 dry_wall:{title:"Trockenmauer / Steinhaufen",category:"structure",icon:"🪨",score:8,supports:["käfer","andere insekten"],tip:"Spalten und sonnige Bereiche nicht vollständig verfugen."},
 nesting_aid:{title:"Insektennisthilfe",category:"structure",icon:"🐝",score:5,supports:["wildbienen"],tip:"Saubere Bohrungen und geeignete Röhrchen sind wichtiger als Größe."},
 wild_corner:{title:"Wilde Ecke",category:"refuge",icon:"🌿",score:8,supports:["schmetterlinge","käfer","andere insekten"],tip:"Möglichst lange ungestört wachsen, verblühen und überwintern lassen."},
 leaf_pile:{title:"Laubhaufen",category:"refuge",icon:"🍂",score:6,supports:["käfer","andere insekten"],tip:"An einer ruhigen Stelle bis ins Frühjahr liegen lassen."},
 brush_pile:{title:"Reisighaufen",category:"refuge",icon:"🪹",score:6,supports:["käfer","andere insekten"],tip:"Locker aufschichten und nicht ständig umsetzen."},
 flower_meadow:{title:"Blühwiese",category:"food",icon:"🌼",score:10,supports:["wildbienen","schmetterlinge","schwebfliegen"],tip:"Regional passendes Saatgut und abschnittsweise Mahd sind besonders wertvoll."},
 herb_bed:{title:"Blühendes Kräuterbeet",category:"food",icon:"🌱",score:8,supports:["wildbienen","schmetterlinge","schwebfliegen"],tip:"Einen Teil der Kräuter bewusst zur Blüte kommen lassen."},
 flowering_border:{title:"Bestäuber-Staudenbeet",category:"food",icon:"🌸",score:9,supports:["wildbienen","schmetterlinge","schwebfliegen"],tip:"Ungefüllte Blüten und gestaffelte Blühzeiten kombinieren."},
 orchard_understory:{title:"Obstbaum mit Unterwuchs",category:"food",icon:"🍎",score:8,supports:["wildbienen","schwebfliegen","käfer"],tip:"Blühenden Unterwuchs nicht während der Blüte komplett mähen."}
};''','defaults')

old_state='var state={days:30,plz:"",loc:null,gardenCenter:null,weather:null,plants:[],zones:[],ecology:{habitat:Object.assign({},DEFAULT_HABITAT)},settings:{plantnetKey:DEFAULT_PLANTNET_KEY,seasonMode:"auto",animations:true,mapView:null,onboardingDismissed:false,plantView:"collection",plantSort:"name"},pendingZone:null,editingZoneId:null,map:null,zoneGroup:null,markerGroup:null,mapReady:false,mapEditMode:false,placePlantId:null,setCenterMode:false,photoData:"",photoFile:null,editPlantId:null};'
new_state='var state={days:30,plz:"",loc:null,gardenCenter:null,weather:null,plants:[],habitats:[],animals:[],zones:[],ecology:{habitat:Object.assign({},DEFAULT_HABITAT),practice:Object.assign({},DEFAULT_PRACTICE)},settings:{plantnetKey:DEFAULT_PLANTNET_KEY,seasonMode:"auto",animations:true,mapView:null,onboardingDismissed:false,plantView:"collection",plantSort:"name",natureTab:"plants"},pendingZone:null,editingZoneId:null,map:null,zoneGroup:null,markerGroup:null,mapReady:false,mapEditMode:false,placePlantId:null,placeHabitatId:null,placeAnimalId:null,setCenterMode:false,photoData:"",photoFile:null,editPlantId:null,habitatPhotoData:"",editHabitatId:null,animalPhotoData:"",editAnimalId:null};'
rep(old_state,new_state,'state')

rep('function normalizeEcology(v){return{habitat:Object.assign({},DEFAULT_HABITAT,v&&v.habitat||{})}}',r'''function normalizeEcology(v){return{habitat:Object.assign({},DEFAULT_HABITAT,v&&v.habitat||{}),practice:Object.assign({},DEFAULT_PRACTICE,v&&v.practice||{},v&&v.habitat?{noPesticides:v.habitat.noPesticides!==false}: {})}}
function normalizeHabitatEntry(h){h=h||{};if(!h.id)h.id=uid();if(!h.status)h.status="present";if(typeof h.favorite!=="boolean")h.favorite=false;if(!h.created)h.created=isoToday();return h}
function normalizeAnimalObservation(a){a=a||{};if(!a.id)a.id=uid();if(!a.date)a.date=isoToday();if(!a.created)a.created=isoToday();if(!a.group)a.group="other";return a}
function migrateLegacyHabitats(oldEco){if(state.habitats.length)return;var h=oldEco&&oldEco.habitat||{},map=[["waterSource","water_station"],["deadwood","deadwood"],["bareSoil","bare_soil"],["wildCorner","wild_corner"]];map.forEach(function(x){if(h[x[0]])state.habitats.push(normalizeHabitatEntry({type:x[1],status:"present",area:"",notes:"Aus der früheren Lebensraum-Einstellung übernommen."}))})}
function nativePlantStatus(){var yes=0,no=0,unknown=0;state.plants.forEach(function(p){if(p.ecoNative==="yes"){yes++;return}if(p.ecoNative==="no"){no++;return}var r=ecoProfileFor(p);if(r&&r.nat>=10)yes++;else if(r&&r.nat<=3)no++;else unknown++});var known=yes+no,ratio=known?yes/known:0,active=known>=5&&ratio>=.60;return{yes:yes,no:no,unknown:unknown,known:known,ratio:ratio,active:active}}
function practiceScore(){var p=state.ecology&&state.ecology.practice||DEFAULT_PRACTICE,n=nativePlantStatus(),v=0;if(p.noPesticides)v+=2;if(p.leaveStemsInWinter)v+=2;if(p.leavesPartlyRemain)v+=1;if(p.peatFree)v+=1;if(p.lessFrequentMowing)v+=1;if(p.reducedNightLight)v+=1;if(n.active)v+=2;return Math.min(10,v)}
function habitatLibraryItem(type){return HABITAT_LIBRARY[type]||{title:"Lebensraum",category:"other",icon:"🌿",score:5,supports:["andere insekten"],tip:"Struktur möglichst naturnah und dauerhaft erhalten."}}
function habitatStatusFactor(v){return{idea:0,planned:.25,present:1,optimized:1.15}[v]||0}
function habitatStatusLabel(v){return{idea:"Idee",planned:"Geplant",present:"Vorhanden",optimized:"Optimiert"}[v]||"Vorhanden"}
function habitatCategoryLabel(v){return{water:"Wasser",structure:"Nistplätze & Struktur",refuge:"Rückzug & Winter",food:"Nahrung"}[v]||"Lebensraum"}
function habitatEntryImpact(h){var d=habitatLibraryItem(h.type);return Math.round(d.score*habitatStatusFactor(h.status)*10)/10}
function habitatCollectionScore(){var cats={water:0,structure:0,refuge:0,food:0},caps={water:3,structure:5,refuge:3,food:4},byType={};state.habitats.forEach(function(h){var d=habitatLibraryItem(h.type);(byType[h.type]||(byType[h.type]=[])).push(h)});Object.keys(byType).forEach(function(t){var d=habitatLibraryItem(t),arr=byType[t].slice().sort(function(a,b){return habitatStatusFactor(b.status)-habitatStatusFactor(a.status)}),raw=0;arr.forEach(function(h,i){raw+=d.score*habitatStatusFactor(h.status)*(i===0?1:i===1?.5:.25)});cats[d.category]=(cats[d.category]||0)+raw});var total=0;Object.keys(caps).forEach(function(c){total+=Math.min(caps[c],Math.round((cats[c]/10*caps[c])*10)/10)});return Math.min(15,Math.round(total))}''','normalizers')

# Replace score model
sub(r'function habitatScore\(h\)\{[^\n]*\}\nfunction gardenEcoScore\(plantsOverride\)\{[^\n]*\}',r'''function habitatScore(){return habitatCollectionScore()}
function gardenEcoScore(plantsOverride){var plants=(plantsOverride||state.plants||[]).map(normalizePlantData),unique={},families=new Set(),types=new Set();plants.forEach(function(p){var k=(p.scientific||p.name||p.id||"").trim().toLowerCase();if(!unique[k]||plantInsectValue(p).score>plantInsectValue(unique[k]).score)unique[k]=p;if(p.family)families.add(String(p.family).toLowerCase());if(p.type)types.add(p.type)});var ups=Object.keys(unique).map(function(k){return unique[k]}),quality=0;if(ups.length){var scores=ups.map(function(p){return plantInsectValue(p).score}).sort(function(a,b){return b-a}).slice(0,20);quality=Math.round((scores.reduce(function(a,b){return a+b},0)/scores.length)*.40)}var counts=Array(12).fill(0);ups.forEach(function(p){plantInsectValue(p).bloomMonths.forEach(function(m){if(m>=1&&m<=12)counts[m-1]++})});var relevant=[2,3,4,5,6,7,8,9],bloom=0,covered=true;relevant.forEach(function(i){if(counts[i]>=2)bloom+=2;else if(counts[i]>=1)bloom+=1;else covered=false});if(covered)bloom+=4;bloom=Math.min(20,bloom);var speciesPts=Math.min(7,Math.round(ups.length*.85)),familyPts=Math.min(4,Math.round(families.size*.9)),typePts=Math.min(4,Math.round(types.size*1.35)),diversity=Math.min(15,speciesPts+familyPts+typePts),hab=habitatCollectionScore(),practice=practiceScore(),total=Math.max(0,Math.min(100,quality+bloom+diversity+hab+practice)),native=nativePlantStatus();return{total:total,quality:quality,bloom:bloom,diversity:diversity,habitat:hab,practice:practice,counts:counts,uniqueCount:ups.length,valuable:plants.filter(function(p){return plantInsectValue(p).score>=70}).length,profiled:plants.filter(function(p){return plantInsectValue(p).source==="Artprofil"}).length,native:native}}''','score model')
sub(r'function bloomGapRecommendation\(g\)\{[^\n]*\}',r'''function bloomGapRecommendation(g){var gaps=[];for(var m=3;m<=10;m++)if(!g.counts[m-1])gaps.push(m);if(gaps.length){var names=gaps.map(function(m){return MONTHS[m-1]});if(gaps.some(function(m){return m<=4}))return"Was jetzt am meisten bringt: mehr Frühblüher für "+names.filter(function(x,i){return gaps[i]<=4}).join(", ")+".";if(gaps.some(function(m){return m>=9}))return"Was jetzt am meisten bringt: mehr Spätblüher für "+names.filter(function(x,i){return gaps[i]>=9}).join(", ")+".";return"Blühlücke: In "+names.join(", ")+" fehlt derzeit eine eingetragene Blühpflanze."}if(g.habitat<8){var cats=new Set(state.habitats.filter(function(h){return h.status==="present"||h.status==="optimized"}).map(function(h){return habitatLibraryItem(h.type).category}));if(!cats.has("structure"))return"Was jetzt am meisten bringt: Nist- oder Strukturraum ergänzen, z. B. offene Bodenstelle, Totholz oder Sandarium.";if(!cats.has("water"))return"Was jetzt am meisten bringt: eine sichere Wasserstelle ergänzen.";return"Zusätzliche Lebensraum-Strukturen würden den Garten weiter aufwerten."}if(g.practice<6)return"Das Blühangebot und die Lebensräume sind gut. Naturnahe Pflege – besonders Winterstängel, Laub und wenig Nachtlicht – bietet noch Potenzial.";return"Sehr ausgewogen: Nahrung, Lebensräume und naturnahe Pflege greifen gut ineinander. Beobachtete Tiere zeigen zusätzlich, wer den Garten tatsächlich nutzt."}''','recommendation')

# ---------- LOAD/SAVE/SYNC ----------
sub(r'function load\(\)\{[^\n]*\}\nfunction loadSync',r'''function load(){try{var raw=localStorage.getItem(STORE);if(raw){var d=JSON.parse(raw);state.plz=d.plz||"";state.loc=d.loc||null;state.gardenCenter=d.gardenCenter||null;state.plants=(Array.isArray(d.plants)?d.plants:[]).map(normalizePlantData);state.habitats=(Array.isArray(d.habitats)?d.habitats:[]).map(normalizeHabitatEntry);state.animals=(Array.isArray(d.animals)?d.animals:[]).map(normalizeAnimalObservation);state.zones=Array.isArray(d.zones)?d.zones:[];state.ecology=normalizeEcology(d.ecology);if(!Array.isArray(d.habitats))migrateLegacyHabitats(d.ecology);state.settings=Object.assign({plantnetKey:DEFAULT_PLANTNET_KEY,seasonMode:"auto",animations:true,mapView:null,onboardingDismissed:false,plantView:"collection",plantSort:"name",natureTab:"plants"},d.settings||{});if(!(state.settings.plantnetKey||"").trim())state.settings.plantnetKey=DEFAULT_PLANTNET_KEY;if(!["auto","spring","summer","autumn","winter"].includes(state.settings.seasonMode))state.settings.seasonMode="auto";if(!["plants","habitats","animals"].includes(state.settings.natureTab))state.settings.natureTab="plants";if(state.settings.animations!==false)state.settings.animations=true;state.days=[7,14,30,60,90].includes(Number(d.days))?Number(d.days):30}else{var old=localStorage.getItem("giess_plz");if(old)state.plz=old}}catch(e){console.warn(e)}loadSync()}
function loadSync''','load',re.S)
sub(r'function cloudPayload\(\)\{[^\n]*\}', 'function cloudPayload(){return{version:3,plz:state.plz||"",loc:state.loc||null,gardenCenter:state.gardenCenter||null,plants:state.plants||[],habitats:state.habitats||[],animals:state.animals||[],zones:state.zones||[],ecology:state.ecology||normalizeEcology(null)}}','cloud payload')
sub(r'function save\(\)\{[^\n]*\}', 'function save(){try{localStorage.setItem(STORE,JSON.stringify({plz:state.plz,loc:state.loc,gardenCenter:state.gardenCenter,plants:state.plants,habitats:state.habitats,animals:state.animals,zones:state.zones,ecology:state.ecology,settings:state.settings,days:state.days}));if(syncState.enabled&&!syncState.applying){var ph=cloudPayloadHash();if(ph&&ph!==syncState.lastPayloadHash){syncState.dirty=true;saveSync();scheduleCloudPush()}}return true}catch(e){globalError("Lokaler Speicher ist voll. Exportiere ein Backup und lösche gegebenenfalls alte Fotos.");return false}}','save')
sub(r'function applyCloudPayload\(p\)\{[^\n]*\}', 'function applyCloudPayload(p){p=p||{};syncState.applying=true;state.plz=p.plz||"";state.loc=p.loc||null;state.gardenCenter=p.gardenCenter||null;state.plants=(Array.isArray(p.plants)?p.plants:[]).map(normalizePlantData);state.habitats=(Array.isArray(p.habitats)?p.habitats:[]).map(normalizeHabitatEntry);state.animals=(Array.isArray(p.animals)?p.animals:[]).map(normalizeAnimalObservation);state.zones=Array.isArray(p.zones)?p.zones:[];state.ecology=normalizeEcology(p.ecology);save();syncState.applying=false;renderAll();if(state.plz)refreshWeather(false)}','apply cloud')

# ---------- ECO DASHBOARD ----------
sub(r'function renderEcoDashboard\(\)\{[^\n]*\}',r'''function renderEcoDashboard(){var g=gardenEcoScore(),score=el("ecoGardenScore"),level=el("ecoGardenLevel"),summary=el("ecoGardenSummary"),stats=el("ecoGardenStats"),bars=el("ecoBloomBars"),labels=el("ecoBloomLabels"),rec=el("ecoRecommendation");if(!score)return;var any=state.plants.length||state.habitats.length;if(!any){score.innerHTML='– <small>/ 100</small>';level.textContent="🐝 Noch keine Bewertung";summary.textContent="Lege Pflanzen und Lebensräume an. Tierbeobachtungen dokumentieren später, wer deinen Garten tatsächlich nutzt.";stats.innerHTML='<span class="eco-stat">0 Pflanzen</span><span class="eco-stat">0 Lebensräume</span>';rec.textContent="Mit der ersten Pflanzen- oder Lebensraumkarte startet die Bewertung."}else{var basis=(state.plants.length>=10||state.habitats.length>=4)?"gute Datengrundlage":(state.plants.length>=5||state.habitats.length>=2)?"mittlere Datengrundlage":"vorläufig";score.innerHTML=g.total+' <small>/ 100</small>';level.textContent="🐝 "+gardenEcoLevel(g.total)+" · "+basis;summary.textContent="Orientierungswert aus Pflanzenqualität, Blühabdeckung, Vielfalt, Lebensräumen und naturnaher Pflege.";stats.innerHTML='<span class="eco-stat">'+g.valuable+' wertvolle Pflanzen</span><span class="eco-stat">'+state.habitats.length+' Lebensräume</span><span class="eco-stat">'+state.animals.length+' Tierbeobachtungen</span>';rec.textContent=bloomGapRecommendation(g)}var breakdown=el("ecoScoreBreakdown");if(!breakdown){breakdown=document.createElement("div");breakdown.id="ecoScoreBreakdown";breakdown.className="score-breakdown";rec.parentNode.insertBefore(breakdown,rec)}breakdown.innerHTML='<div class="score-part"><b>'+g.quality+'/40</b><small>Pflanzen</small></div><div class="score-part"><b>'+g.bloom+'/20</b><small>Blüte</small></div><div class="score-part"><b>'+g.diversity+'/15</b><small>Vielfalt</small></div><div class="score-part"><b>'+g.habitat+'/15</b><small>Lebensräume</small></div><div class="score-part"><b>'+g.practice+'/10</b><small>Pflege</small></div>';bars.innerHTML=g.counts.map(function(n){return'<span class="'+(n>=2?'good':n===1?'some':'')+'" title="'+n+' blühende '+(n===1?'Art':'Arten')+'"></span>'}).join("");labels.innerHTML=MONTHS.map(function(m){return'<span>'+m.slice(0,1)+'</span>'}).join("");renderPracticeSettings(g)}''','eco dashboard')

# ---------- NATURGARTEN FUNCTIONS ----------
insert=r'''
function setNatureTab(tab,doSave){tab=["plants","habitats","animals"].includes(tab)?tab:"plants";state.settings.natureTab=tab;show("naturePlantsPane",tab==="plants");show("natureHabitatsPane",tab==="habitats");show("natureAnimalsPane",tab==="animals");document.querySelectorAll(".nature-tab").forEach(function(b){b.classList.toggle("active",b.dataset.nature===tab)});if(doSave!==false)save();if(tab==="habitats")renderHabitats();if(tab==="animals")renderAnimals()}
function renderNatureTabs(){if(el("naturePlantCount"))el("naturePlantCount").textContent=state.plants.length;if(el("natureHabitatCount"))el("natureHabitatCount").textContent=state.habitats.length;if(el("natureAnimalCount"))el("natureAnimalCount").textContent=state.animals.length;setNatureTab(state.settings.natureTab||"plants",false)}
function populateHabitatTypes(){var sel=el("habitatType");if(!sel)return;sel.innerHTML=Object.keys(HABITAT_LIBRARY).map(function(k){var d=HABITAT_LIBRARY[k];return'<option value="'+k+'">'+d.icon+' '+esc(d.title)+' · '+esc(habitatCategoryLabel(d.category))+'</option>'}).join("")}
function renderHabitatFilters(){var cats=[["all","Alle"],["water","Wasser"],["structure","Struktur & Nistplätze"],["refuge","Rückzug"],["food","Nahrung"],["planned","Geplant"]],box=el("habitatFilters");if(!box)return;var active=box.dataset.active||"all";box.innerHTML=cats.map(function(c){return'<button class="library-filter '+(active===c[0]?'active':'')+'" data-filter="'+c[0]+'" type="button">'+c[1]+'</button>'}).join("");box.querySelectorAll(".library-filter").forEach(function(b){b.addEventListener("click",function(){box.dataset.active=b.dataset.filter;renderHabitats()})})}
function habitatCardHtml(h){var d=habitatLibraryItem(h.type),impact=habitatEntryImpact(h),photo=h.photo?'<img src="'+h.photo+'" alt="'+esc(d.title)+'">':d.icon,status=habitatStatusLabel(h.status),chipClass=h.status==="present"||h.status==="optimized"?"good":h.status==="planned"?"plan":"";return'<article class="nature-card"><button class="nature-card-main habitatOpen" data-id="'+h.id+'" type="button"><div class="nature-card-photo">'+photo+'<span class="nature-impact">🐝 '+impact+'</span></div><div class="nature-card-body"><div class="nature-card-name">'+esc(d.title)+'</div><div class="nature-card-sub">'+esc(h.area||habitatCategoryLabel(d.category))+'</div><div class="nature-card-meta"><span class="nature-chip '+chipClass+'">'+esc(status)+'</span><span class="nature-chip">'+esc(habitatCategoryLabel(d.category))+'</span></div></div></button></article>'}
function renderHabitats(){var box=el("habitatList");if(!box)return;renderHabitatFilters();var q=(el("habitatSearch")&&el("habitatSearch").value||"").trim().toLowerCase(),filter=el("habitatFilters").dataset.active||"all",items=state.habitats.filter(function(h){var d=habitatLibraryItem(h.type);if(q&&!(d.title.toLowerCase().includes(q)||String(h.area||"").toLowerCase().includes(q)||String(h.notes||"").toLowerCase().includes(q)))return false;if(filter==="planned")return h.status==="planned"||h.status==="idea";if(filter!=="all")return d.category===filter;return true});box.innerHTML=items.length?items.map(habitatCardHtml).join(""):'<div class="box empty" style="grid-column:1/-1">Noch keine passenden Lebensräume gespeichert.</div>';box.querySelectorAll(".habitatOpen").forEach(function(b){b.addEventListener("click",function(){openHabitatDetail(b.dataset.id)})})}
function resetHabitatForm(){el("habitatForm").reset();el("habitatId").value="";el("habitatStatus").value="present";state.editHabitatId=null;state.habitatPhotoData="";el("habitatPhotoPreview").textContent="Foto";renderHabitatImpactPreview()}
function openHabitatEditor(id){resetHabitatForm();var h=id?state.habitats.find(function(x){return x.id===id}):null;state.editHabitatId=h?h.id:null;el("habitatEditorTitle").textContent=h?"Lebensraum bearbeiten":"Lebensraum hinzufügen";if(h){el("habitatId").value=h.id;el("habitatType").value=h.type;el("habitatStatus").value=h.status||"present";el("habitatArea").value=h.area||"";el("habitatNotes").value=h.notes||"";state.habitatPhotoData=h.photo||"";if(h.photo)el("habitatPhotoPreview").innerHTML='<img src="'+h.photo+'" alt="Vorschau">'}show("habitatEditor",true);renderHabitatImpactPreview();el("habitatEditor").scrollIntoView({behavior:"smooth",block:"start"})}
function renderHabitatImpactPreview(){var box=el("habitatImpactPreview");if(!box)return;var type=el("habitatType").value||Object.keys(HABITAT_LIBRARY)[0],status=el("habitatStatus").value||"present",d=habitatLibraryItem(type),impact=Math.round(d.score*habitatStatusFactor(status)*10)/10;box.innerHTML='<b>'+d.icon+' '+esc(d.title)+' · Nutzen '+impact+'</b><br><span class="muted">'+esc(d.tip)+'</span>'}
function habitatFromForm(){var old=state.editHabitatId?state.habitats.find(function(x){return x.id===state.editHabitatId}):null;return normalizeHabitatEntry({id:old?old.id:uid(),type:el("habitatType").value,status:el("habitatStatus").value,area:el("habitatArea").value.trim(),photo:state.habitatPhotoData||"",notes:el("habitatNotes").value.trim(),favorite:old?!!old.favorite:false,lat:old?old.lat:null,lon:old?old.lon:null,created:old?old.created:isoToday()})}
function saveHabitat(placeAfter){var h=habitatFromForm(),i=state.habitats.findIndex(function(x){return x.id===h.id});if(i>=0)state.habitats[i]=h;else state.habitats.push(h);if(!save())return;show("habitatEditor",false);renderAll();if(placeAfter)beginPlaceHabitat(h.id)}
function beginPlaceHabitat(id){var h=state.habitats.find(function(x){return x.id===id});if(!h)return;state.placeHabitatId=id;state.placePlantId=null;state.placeAnimalId=null;switchView("map");setTimeout(function(){setMapEditing(true);el("mapModeHint").textContent='Auf das Luftbild tippen, um „'+habitatLibraryItem(h.type).title+'“ zu positionieren.';show("mapModeHint",true)},90)}
function openHabitatDetail(id){var h=state.habitats.find(function(x){return x.id===id});if(!h)return;var d=habitatLibraryItem(h.type),photo=h.photo?'<img src="'+h.photo+'" alt="'+esc(d.title)+'">':d.icon,supports=(d.supports||[]).map(function(x){return'<span class="support-chip">'+esc(supportLabel(x))+'</span>'}).join('');el("plantDetailHeading").textContent=d.title;el("plantDetailContent").innerHTML='<div class="detail-hero">'+photo+'<span class="insect-badge high">🐝 Nutzen '+habitatEntryImpact(h)+'</span></div><div class="detail-title"><div><h3>'+esc(d.title)+'</h3><div class="muted">'+esc(h.area||habitatCategoryLabel(d.category))+'</div></div></div><div class="detail-section"><h4>Status</h4><div class="detail-grid"><div class="detail-kv"><span>Status</span><b>'+esc(habitatStatusLabel(h.status))+'</b></div><div class="detail-kv"><span>Kategorie</span><b>'+esc(habitatCategoryLabel(d.category))+'</b></div></div></div><div class="detail-section"><h4>Warum wertvoll?</h4><div class="muted">'+esc(d.tip)+'</div><div class="support-chips">'+supports+'</div></div>'+(h.notes?'<div class="detail-section"><h4>Notizen</h4><div class="muted">'+esc(h.notes)+'</div></div>':'')+'<div class="actions" style="margin-top:14px"><button class="btn habitatDetailEdit" data-id="'+h.id+'">Bearbeiten</button><button class="btn secondary habitatDetailPlace" data-id="'+h.id+'">'+(h.lat?'Position ändern':'Auf Karte setzen')+'</button><button class="btn ghost habitatDetailDelete" data-id="'+h.id+'">Löschen</button></div>';el("plantDetailOverlay").classList.remove("hidden");el("plantDetailOverlay").setAttribute("aria-hidden","false");document.body.classList.add("settings-open");el("plantDetailContent").querySelector(".habitatDetailEdit").addEventListener("click",function(){closePlantDetail();setNatureTab("habitats");openHabitatEditor(h.id)});el("plantDetailContent").querySelector(".habitatDetailPlace").addEventListener("click",function(){closePlantDetail();beginPlaceHabitat(h.id)});el("plantDetailContent").querySelector(".habitatDetailDelete").addEventListener("click",function(){if(confirm("Diesen Lebensraum löschen?")){closePlantDetail();state.habitats=state.habitats.filter(function(x){return x.id!==h.id});save();renderAll()}})}
function populateAnimalLinks(){var ps=el("animalLinkedPlant"),hs=el("animalLinkedHabitat");if(ps)ps.innerHTML='<option value="">– keine / unbekannt –</option>'+state.plants.slice().sort(function(a,b){return a.name.localeCompare(b.name,"de")}).map(function(p){return'<option value="'+p.id+'">'+esc(p.name)+(p.area?' · '+esc(p.area):'')+'</option>'}).join('');if(hs)hs.innerHTML='<option value="">– keiner / unbekannt –</option>'+state.habitats.map(function(h){var d=habitatLibraryItem(h.type);return'<option value="'+h.id+'">'+esc(d.title)+(h.area?' · '+esc(h.area):'')+'</option>'}).join('')}
function animalGroupLabel(v){return{insect:"Insekt",butterfly:"Schmetterling / Nachtfalter",bee:"Biene / Hummel / Wespe",beetle:"Käfer",spider:"Spinne",bird:"Vogel",mammal:"Säugetier",amphibian:"Amphibie",reptile:"Reptil",mollusc:"Schnecke / Weichtier",other:"Andere"}[v]||"Tier"}
function animalGroupIcon(v){return{insect:"🐞",butterfly:"🦋",bee:"🐝",beetle:"🐞",spider:"🕷️",bird:"🐦",mammal:"🦔",amphibian:"🐸",reptile:"🦎",mollusc:"🐌",other:"🐾"}[v]||"🐾"}
function inatGroup(t){var n=String(t.iconic_taxon_name||"").toLowerCase(),ids=t.ancestor_ids||[];if(ids.includes(47157))return"butterfly";if(ids.includes(47208))return"beetle";if(ids.includes(47201))return"bee";if(n==="arachnida")return"spider";if(n==="aves")return"bird";if(n==="mammalia")return"mammal";if(n==="amphibia")return"amphibian";if(n==="reptilia")return"reptile";if(n==="mollusca")return"mollusc";if(n==="insecta")return"insect";return"other"}
function resetAnimalForm(){el("animalForm").reset();el("animalId").value="";el("animalTaxonId").value="";el("animalScientific").value="";el("animalRefPhoto").value="";el("animalRefAttribution").value="";el("animalDate").value=isoToday();state.editAnimalId=null;state.animalPhotoData="";el("animalPhotoPreview").textContent="Foto optional";el("animalReferenceNote").textContent="";el("animalTaxonAssist").textContent="Ab 3 Zeichen durchsucht die Gartenwelt kostenlos iNaturalist.";show("animalTaxonResults",false);populateAnimalLinks()}
function openAnimalEditor(id,preset){resetAnimalForm();var a=id?state.animals.find(function(x){return x.id===id}):null;state.editAnimalId=a?a.id:null;el("animalEditorTitle").textContent=a?"Beobachtung bearbeiten":"Tier beobachten";if(a){el("animalId").value=a.id;el("animalTaxonId").value=a.taxonId||"";el("animalName").value=a.name||"";el("animalScientific").value=a.scientific||"";el("animalRefPhoto").value=a.refPhoto||"";el("animalRefAttribution").value=a.refAttribution||"";el("animalGroup").value=a.group||"other";el("animalDate").value=a.date||isoToday();el("animalArea").value=a.area||"";el("animalLinkedPlant").value=a.linkedPlantId||"";el("animalLinkedHabitat").value=a.linkedHabitatId||"";el("animalNotes").value=a.notes||"";state.animalPhotoData=a.photo||"";if(a.photo)el("animalPhotoPreview").innerHTML='<img src="'+a.photo+'" alt="Vorschau">';else if(a.refPhoto){el("animalPhotoPreview").innerHTML='<img src="'+a.refPhoto+'" alt="Referenzbild">';el("animalReferenceNote").textContent="Referenzbild aus iNaturalist · "+(a.refAttribution||"Lizenzangaben beim Quellbild")}}else if(preset){el("animalTaxonId").value=preset.taxonId||"";el("animalName").value=preset.name||"";el("animalScientific").value=preset.scientific||"";el("animalRefPhoto").value=preset.refPhoto||"";el("animalRefAttribution").value=preset.refAttribution||"";el("animalGroup").value=preset.group||"other";if(preset.refPhoto){el("animalPhotoPreview").innerHTML='<img src="'+preset.refPhoto+'" alt="Referenzbild">';el("animalReferenceNote").textContent="Referenzbild aus iNaturalist · "+(preset.refAttribution||"Lizenzangaben beim Quellbild")}}show("animalEditor",true);el("animalEditor").scrollIntoView({behavior:"smooth",block:"start"})}
function animalFromForm(){var name=el("animalName").value.trim();if(!name)throw new Error("Bitte einen Tiernamen eingeben.");var old=state.editAnimalId?state.animals.find(function(x){return x.id===state.editAnimalId}):null;return normalizeAnimalObservation({id:old?old.id:uid(),taxonId:el("animalTaxonId").value||"",name:name,scientific:el("animalScientific").value.trim(),group:el("animalGroup").value,date:el("animalDate").value||isoToday(),area:el("animalArea").value.trim(),linkedPlantId:el("animalLinkedPlant").value||"",linkedHabitatId:el("animalLinkedHabitat").value||"",photo:state.animalPhotoData||"",refPhoto:el("animalRefPhoto").value||"",refAttribution:el("animalRefAttribution").value||"",notes:el("animalNotes").value.trim(),lat:old?old.lat:null,lon:old?old.lon:null,created:old?old.created:isoToday()})}
function saveAnimal(placeAfter){try{var a=animalFromForm(),i=state.animals.findIndex(function(x){return x.id===a.id});if(i>=0)state.animals[i]=a;else state.animals.push(a);if(!save())return;show("animalEditor",false);renderAll();if(placeAfter)beginPlaceAnimal(a.id)}catch(e){globalError(e.message)}}
function beginPlaceAnimal(id){var a=state.animals.find(function(x){return x.id===id});if(!a)return;state.placeAnimalId=id;state.placePlantId=null;state.placeHabitatId=null;switchView("map");setTimeout(function(){setMapEditing(true);el("mapModeHint").textContent='Auf das Luftbild tippen, wo „'+a.name+'“ beobachtet wurde.';show("mapModeHint",true)},90)}
var animalTaxonTimer=null,animalTaxonSeq=0;
function hideAnimalTaxonResults(){el("animalTaxonResults").innerHTML="";show("animalTaxonResults",false)}
function applyInatTaxon(t){var photo=t.default_photo||{},name=t.preferred_common_name||t.matched_term||t.name||"";el("animalName").value=name;el("animalScientific").value=t.name||"";el("animalTaxonId").value=t.id||"";el("animalGroup").value=inatGroup(t);el("animalRefPhoto").value=photo.medium_url||photo.square_url||"";el("animalRefAttribution").value=photo.attribution||"";if(!state.animalPhotoData&&el("animalRefPhoto").value)el("animalPhotoPreview").innerHTML='<img src="'+el("animalRefPhoto").value+'" alt="Referenzbild">';el("animalReferenceNote").textContent=el("animalRefPhoto").value?"Referenzbild aus iNaturalist · "+(photo.attribution||"Lizenzangaben beim Quellbild"):"";el("animalTaxonAssist").textContent="Aus iNaturalist übernommen. Du kannst die Beobachtung jetzt speichern.";hideAnimalTaxonResults()}
function renderAnimalTaxonResults(rs){var box=el("animalTaxonResults");if(!rs.length){hideAnimalTaxonResults();el("animalTaxonAssist").textContent="Kein passender Tiername gefunden – du kannst den Namen trotzdem frei eintragen.";return}box.innerHTML=rs.map(function(t,i){var photo=t.default_photo||{},name=t.preferred_common_name||t.matched_term||t.name||"",thumb=photo.square_url?'<img src="'+photo.square_url+'" alt="">':animalGroupIcon(inatGroup(t));return'<button class="tax-result" type="button" data-i="'+i+'"><span class="tax-thumb">'+thumb+'</span><span><b>'+esc(name)+'</b><small>'+esc(t.name||'')+' · '+esc(animalGroupLabel(inatGroup(t)))+'</small></span></button>'}).join("");show("animalTaxonResults",true);box.querySelectorAll(".tax-result").forEach(function(b){b.addEventListener("click",function(){applyInatTaxon(rs[Number(b.dataset.i)])})})}
async function searchInaturalistTaxa(q){q=String(q||"").trim();if(q.length<3){hideAnimalTaxonResults();el("animalTaxonAssist").textContent="Ab 3 Zeichen durchsucht die Gartenwelt kostenlos iNaturalist.";return}var seq=++animalTaxonSeq;el("animalTaxonAssist").textContent="iNaturalist wird durchsucht …";try{var url="https://api.inaturalist.org/v1/taxa/autocomplete?q="+encodeURIComponent(q)+"&taxon_id=1&locale=de&per_page=8",res=await fetch(url,{headers:{"Accept":"application/json"}});if(!res.ok)throw new Error("HTTP "+res.status);var data=await res.json();if(seq!==animalTaxonSeq)return;var rs=(data.results||[]).filter(function(t){return String(t.iconic_taxon_name||"").toLowerCase()!=="plantae"}).slice(0,8);renderAnimalTaxonResults(rs);if(rs.length)el("animalTaxonAssist").textContent="Treffer antippen oder den Namen frei weiterschreiben."}catch(e){if(seq!==animalTaxonSeq)return;hideAnimalTaxonResults();el("animalTaxonAssist").textContent="iNaturalist ist gerade nicht erreichbar – die Beobachtung kann trotzdem manuell gespeichert werden."}}
function animalKey(a){return a.taxonId?"inat:"+a.taxonId:"name:"+String(a.scientific||a.name||"").trim().toLowerCase()}
function animalGroups(){var g={};state.animals.forEach(function(a){var k=animalKey(a);if(!g[k])g[k]={key:k,items:[]};g[k].items.push(a)});return Object.keys(g).map(function(k){var x=g[k];x.items.sort(function(a,b){return String(b.date).localeCompare(String(a.date))});x.latest=x.items[0];return x}).sort(function(a,b){return String(b.latest.date).localeCompare(String(a.latest.date))})}
function animalCardHtml(g){var a=g.latest,photo=a.photo||a.refPhoto||"",visual=photo?'<img src="'+photo+'" alt="'+esc(a.name)+'">':animalGroupIcon(a.group),linked=linkedObservationText(a);return'<article class="nature-card"><button class="nature-card-main animalOpen" data-key="'+esc(g.key)+'" type="button"><div class="nature-card-photo">'+visual+'<span class="species-count">'+g.items.length+'× beobachtet</span></div><div class="nature-card-body"><div class="nature-card-name">'+esc(a.name)+'</div><div class="nature-card-sub">'+esc(a.scientific||animalGroupLabel(a.group))+'</div><div class="nature-card-meta"><span class="nature-chip good">'+animalGroupIcon(a.group)+' '+esc(animalGroupLabel(a.group))+'</span><span class="nature-chip">'+esc(a.date?fmtDate(a.date):'')+'</span></div>'+(linked?'<div class="nature-card-sub" style="margin-top:7px">'+esc(linked)+'</div>':'')+'</div></button></article>'}
function linkedObservationText(a){var p=state.plants.find(function(x){return x.id===a.linkedPlantId}),h=state.habitats.find(function(x){return x.id===a.linkedHabitatId}),parts=[];if(p)parts.push("an "+p.name);if(h)parts.push("bei "+habitatLibraryItem(h.type).title);return parts.join(" · ")}
function renderAnimals(){var box=el("animalList");if(!box)return;var q=(el("animalCollectionSearch")&&el("animalCollectionSearch").value||"").trim().toLowerCase(),groups=animalGroups().filter(function(g){var a=g.latest;return !q||String(a.name||"").toLowerCase().includes(q)||String(a.scientific||"").toLowerCase().includes(q)||String(a.area||"").toLowerCase().includes(q)||animalGroupLabel(a.group).toLowerCase().includes(q)});box.innerHTML=groups.length?groups.map(animalCardHtml).join(""):'<div class="box empty" style="grid-column:1/-1">Noch keine Tierbeobachtungen gespeichert.</div>';box.querySelectorAll(".animalOpen").forEach(function(b){b.addEventListener("click",function(){openAnimalDetail(b.dataset.key)})})}
function openAnimalDetail(key){var g=animalGroups().find(function(x){return x.key===key});if(!g)return;var a=g.latest,photo=a.photo||a.refPhoto||"",visual=photo?'<img src="'+photo+'" alt="'+esc(a.name)+'">':animalGroupIcon(a.group),rows=g.items.map(function(o){return'<div class="observation-row"><div><b>'+esc(o.date?fmtDate(o.date):'Datum unbekannt')+(o.area?' · '+esc(o.area):'')+'</b><small>'+esc(linkedObservationText(o)||'ohne Verknüpfung')+(o.notes?' · '+esc(o.notes):'')+'</small></div><div class="actions"><button class="btn ghost small animalObsEdit" data-id="'+o.id+'">Bearbeiten</button><button class="btn ghost small animalObsDelete" data-id="'+o.id+'">×</button></div></div>'}).join(''),preset={taxonId:a.taxonId,name:a.name,scientific:a.scientific,group:a.group,refPhoto:a.refPhoto,refAttribution:a.refAttribution};el("plantDetailHeading").textContent=a.name;el("plantDetailContent").innerHTML='<div class="detail-hero">'+visual+'<span class="insect-badge high">'+animalGroupIcon(a.group)+' '+esc(animalGroupLabel(a.group))+'</span></div><div class="detail-title"><div><h3>'+esc(a.name)+'</h3><div class="latin">'+esc(a.scientific||'')+'</div><div class="muted">'+g.items.length+' Beobachtung'+(g.items.length===1?'':'en')+'</div></div></div><div class="detail-section"><h4>Beobachtungen</h4><div class="observation-list">'+rows+'</div></div>'+(a.refPhoto?'<div class="reference-note">Referenzbild aus iNaturalist · '+esc(a.refAttribution||'Lizenzangaben beim Quellbild')+'</div>':'')+'<div class="actions" style="margin-top:14px"><button class="btn animalAddSame">+ weitere Beobachtung</button></div>';el("plantDetailOverlay").classList.remove("hidden");el("plantDetailOverlay").setAttribute("aria-hidden","false");document.body.classList.add("settings-open");el("plantDetailContent").querySelector(".animalAddSame").addEventListener("click",function(){closePlantDetail();setNatureTab("animals");openAnimalEditor(null,preset)});el("plantDetailContent").querySelectorAll(".animalObsEdit").forEach(function(b){b.addEventListener("click",function(){closePlantDetail();setNatureTab("animals");openAnimalEditor(b.dataset.id)})});el("plantDetailContent").querySelectorAll(".animalObsDelete").forEach(function(b){b.addEventListener("click",function(){if(confirm("Diese Beobachtung löschen?")){state.animals=state.animals.filter(function(x){return x.id!==b.dataset.id});save();closePlantDetail();renderAll()}})})}
function renderPracticeSettings(g){g=g||gardenEcoScore();var n=nativePlantStatus(),box=el("nativePlantAutoStatus");document.querySelectorAll('[data-practice]').forEach(function(c){c.checked=!!(state.ecology&&state.ecology.practice&&state.ecology.practice[c.dataset.practice])});if(box){if(n.known>=5)box.innerHTML='<b>Heimische Pflanzen: '+(n.active?'automatisch erkannt ✓':'noch nicht überwiegend')+'</b><br>'+n.yes+' von '+n.known+' bewertbaren Pflanzen gelten als heimisch/regional ('+Math.round(n.ratio*100)+' %).'+(n.unknown?' '+n.unknown+' Pflanze'+(n.unknown===1?'':'n')+' noch ohne sichere Einordnung.':'');else box.innerHTML='<b>Heimische Pflanzen: noch zu wenig Daten</b><br>'+n.known+' Pflanze'+(n.known===1?'':'n')+' bewertbar. Ab 5 bewertbaren Pflanzen wird „überwiegend heimisch“ automatisch ab 60 % erkannt.'}var t=el("practiceScoreText");if(t)t.textContent="Naturnahe Praxis: "+g.practice+" / 10 Punkten · Lebensräume aus Karten: "+g.habitat+" / 15 Punkten."}
'''
rep('function buildMonthChecks(containerId,name){',insert+'\nfunction buildMonthChecks(containerId,name){','nature functions')

# ---------- MAP placement & markers ----------
rep('function beginPlacePlant(id){var p=state.plants.find(function(x){return x.id===id});if(!p)return;state.placePlantId=id;state.setCenterMode=false;switchView("map");setTimeout(function(){setMapEditing(true);el("mapModeHint").textContent=\'Auf das Luftbild tippen, um „\'+p.name+\'“ zu positionieren.\';show("mapModeHint",true)},90)}', 'function beginPlacePlant(id){var p=state.plants.find(function(x){return x.id===id});if(!p)return;state.placePlantId=id;state.placeHabitatId=null;state.placeAnimalId=null;state.setCenterMode=false;switchView("map");setTimeout(function(){setMapEditing(true);el("mapModeHint").textContent=\'Auf das Luftbild tippen, um „\'+p.name+\'“ zu positionieren.\';show("mapModeHint",true)},90)}','plant place reset')
oldclick='if(state.placePlantId){var p=state.plants.find(function(x){return x.id===state.placePlantId});if(p){p.lat=e.latlng.lat;p.lon=e.latlng.lng;state.placePlantId=null;show("mapModeHint",false);save();renderAll();notice("Pflanze auf der Karte positioniert.")}}'
newclick=oldclick+'else if(state.placeHabitatId){var h=state.habitats.find(function(x){return x.id===state.placeHabitatId});if(h){h.lat=e.latlng.lat;h.lon=e.latlng.lng;state.placeHabitatId=null;show("mapModeHint",false);save();renderAll();notice("Lebensraum auf der Karte positioniert.")}}else if(state.placeAnimalId){var a=state.animals.find(function(x){return x.id===state.placeAnimalId});if(a){a.lat=e.latlng.lat;a.lon=e.latlng.lng;state.placeAnimalId=null;show("mapModeHint",false);save();renderAll();notice("Beobachtungsort gespeichert.")}}'
rep(oldclick,newclick,'map click placement')
# insert nature markers into renderMap just before renderZoneList
needle='});renderZoneList();renderMapMode()}'
idx=s.find('function renderMap()')
pos=s.find(needle,idx)
if pos<0: raise SystemExit('renderMap tail not found')
extra='});state.habitats.filter(function(h){return h.lat&&h.lon}).forEach(function(h){var d=habitatLibraryItem(h.type),icon=L.divIcon({className:"",html:\'<div class="map-nature-marker">\'+d.icon+\'</div>\',iconSize:[28,28],iconAnchor:[14,14]}),m=L.marker([h.lat,h.lon],{icon:icon,draggable:!!state.mapEditMode}).addTo(state.markerGroup);m.bindPopup(\'<b>\'+esc(d.title)+\'</b><br>\'+esc(habitatStatusLabel(h.status)));if(state.mapEditMode)m.on("dragend",function(){var q=m.getLatLng();h.lat=q.lat;h.lon=q.lng;save();renderAll()})});state.animals.filter(function(a){return a.lat&&a.lon}).forEach(function(a){var icon=L.divIcon({className:"",html:\'<div class="map-nature-marker map-animal-marker">\'+animalGroupIcon(a.group)+\'</div>\',iconSize:[28,28],iconAnchor:[14,14]}),m=L.marker([a.lat,a.lon],{icon:icon,draggable:!!state.mapEditMode}).addTo(state.markerGroup);m.bindPopup(\'<b>\'+esc(a.name)+\'</b><br>beobachtet \'+esc(a.date?fmtDate(a.date):\'\'));if(state.mapEditMode)m.on("dragend",function(){var q=m.getLatLng();a.lat=q.lat;a.lon=q.lng;save();renderAll()})});renderZoneList();renderMapMode()}'
s=s[:pos]+extra+s[pos+len(needle):]
sub(r'function fitGarden\(\)\{[^\n]*\}', 'function fitGarden(){if(!state.mapReady)return;var pts=[];if(state.gardenCenter)pts.push([state.gardenCenter.lat,state.gardenCenter.lon]);state.plants.forEach(function(p){if(p.lat&&p.lon)pts.push([p.lat,p.lon])});state.habitats.forEach(function(h){if(h.lat&&h.lon)pts.push([h.lat,h.lon])});state.animals.forEach(function(a){if(a.lat&&a.lon)pts.push([a.lat,a.lon])});state.zones.forEach(function(z){z.points.forEach(function(p){pts.push([p.lat,p.lon])})});if(pts.length)state.map.fitBounds(L.latLngBounds(pts).pad(.2),{maxZoom:21});else if(state.gardenCenter)state.map.setView([state.gardenCenter.lat,state.gardenCenter.lon],20);else if(state.loc)state.map.setView([state.loc.lat,state.loc.lon],19)}','fit garden')

# ---------- RENDER ALL + BACKUP ----------
rep('function renderAll(){applyAppearance();renderOnboardingGuide();renderHeader();renderToday();renderPlants();renderCalendar();renderWeather();renderSync();if(state.mapReady)renderMap()}', 'function renderAll(){applyAppearance();renderOnboardingGuide();renderHeader();renderToday();renderPlants();renderNatureTabs();renderHabitats();renderAnimals();renderCalendar();renderWeather();renderSync();if(state.mapReady)renderMap()}','render all')
sub(r'function exportBackup\(\)\{[^\n]*\}', 'function exportBackup(){var data={version:9,exported:new Date().toISOString(),plz:state.plz,loc:state.loc,gardenCenter:state.gardenCenter,plants:state.plants,habitats:state.habitats,animals:state.animals,zones:state.zones,ecology:state.ecology,settings:{plantnetKey:state.settings.plantnetKey||"",seasonMode:state.settings.seasonMode||"auto",animations:state.settings.animations!==false,mapView:state.settings.mapView||null,plantView:state.settings.plantView||"collection",plantSort:state.settings.plantSort||"name",natureTab:state.settings.natureTab||"plants"},days:state.days};var blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="Johannas_Gartenwelt_Backup_"+isoToday()+".json";document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(a.href);a.remove()},300)}','export backup')
sub(r'async function importBackup\(file\)\{[^\n]*\}', 'async function importBackup(file){try{var data=JSON.parse(await file.text());if(!Array.isArray(data.plants)||!Array.isArray(data.zones))throw new Error("Keine gültige Johanna´s-Gartenwelt-Sicherung");state.plz=data.plz||state.plz;state.loc=data.loc||null;state.gardenCenter=data.gardenCenter||null;state.plants=data.plants.map(normalizePlantData);state.habitats=(Array.isArray(data.habitats)?data.habitats:[]).map(normalizeHabitatEntry);state.animals=(Array.isArray(data.animals)?data.animals:[]).map(normalizeAnimalObservation);state.zones=data.zones;state.ecology=normalizeEcology(data.ecology);if(!Array.isArray(data.habitats))migrateLegacyHabitats(data.ecology);state.days=[7,14,30,60,90].includes(Number(data.days))?Number(data.days):30;state.settings=Object.assign({plantnetKey:DEFAULT_PLANTNET_KEY,seasonMode:"auto",animations:true,mapView:null,plantView:"collection",plantSort:"name",natureTab:"plants"},state.settings||{},data.settings||{});if(data.settings&&Object.prototype.hasOwnProperty.call(data.settings,"plantnetKey"))state.settings.plantnetKey=data.settings.plantnetKey||"";save();renderAll();if(state.plz)refreshWeather(false);notice("Backup importiert.")}catch(e){globalError("Import fehlgeschlagen: "+e.message)}}','import backup')

# ---------- EVENTS ----------
rep('load();applyAppearance();buildMonthChecks("fertMonths","fert");buildMonthChecks("cutMonths","cut");buildMonthChecks("bloomMonths","bloom");', 'load();applyAppearance();buildMonthChecks("fertMonths","fert");buildMonthChecks("cutMonths","cut");buildMonthChecks("bloomMonths","bloom");populateHabitatTypes();populateAnimalLinks();','init')
rep('el("quickAddPlant").addEventListener("click",function(){switchView("plants");setTimeout(function(){openPlantEditor(null)},50)});', 'el("quickAddPlant").addEventListener("click",function(){switchView("plants");setNatureTab("plants");setTimeout(function(){openPlantEditor(null)},50)});','quick add')
rep('el("setupPlantBtn").addEventListener("click",function(){switchView("plants");setTimeout(function(){openPlantEditor(null)},60)});', 'el("setupPlantBtn").addEventListener("click",function(){switchView("plants");setNatureTab("plants");setTimeout(function(){openPlantEditor(null)},60)});','setup plant')
rep('document.querySelectorAll("[data-habitat]").forEach(function(c){c.addEventListener("change",function(){state.ecology=normalizeEcology(state.ecology);state.ecology.habitat[c.dataset.habitat]=!!c.checked;save();renderEcoDashboard()})});', 'document.querySelectorAll("[data-practice]").forEach(function(c){c.addEventListener("change",function(){state.ecology=normalizeEcology(state.ecology);state.ecology.practice[c.dataset.practice]=!!c.checked;save();renderEcoDashboard()})});','practice events')
events=r'''
document.querySelectorAll(".nature-tab").forEach(function(b){b.addEventListener("click",function(){setNatureTab(b.dataset.nature)})});
el("habitatSearch").addEventListener("input",renderHabitats);
el("newHabitatBtn").addEventListener("click",function(){openHabitatEditor(null)});
el("closeHabitatEditor").addEventListener("click",function(){show("habitatEditor",false)});
el("habitatType").addEventListener("change",renderHabitatImpactPreview);
el("habitatStatus").addEventListener("change",renderHabitatImpactPreview);
el("habitatPhoto").addEventListener("change",async function(){var f=this.files&&this.files[0];if(!f)return;try{state.habitatPhotoData=await compressPhoto(f);el("habitatPhotoPreview").innerHTML='<img src="'+state.habitatPhotoData+'" alt="Vorschau">'}catch(e){globalError(e.message)}});
el("habitatForm").addEventListener("submit",function(e){e.preventDefault();saveHabitat(false)});
el("saveHabitatAndPlaceBtn").addEventListener("click",function(){saveHabitat(true)});
el("animalCollectionSearch").addEventListener("input",renderAnimals);
el("newAnimalBtn").addEventListener("click",function(){openAnimalEditor(null)});
el("closeAnimalEditor").addEventListener("click",function(){show("animalEditor",false);hideAnimalTaxonResults()});
el("animalName").addEventListener("input",function(){el("animalTaxonId").value="";el("animalScientific").value="";el("animalRefPhoto").value="";el("animalRefAttribution").value="";clearTimeout(animalTaxonTimer);var q=this.value;animalTaxonTimer=setTimeout(function(){searchInaturalistTaxa(q)},350)});
el("animalName").addEventListener("focus",function(){if(this.value.trim().length>=3&&!el("animalTaxonId").value)searchInaturalistTaxa(this.value)});
el("animalPhoto").addEventListener("change",async function(){var f=this.files&&this.files[0];if(!f)return;try{state.animalPhotoData=await compressPhoto(f);el("animalPhotoPreview").innerHTML='<img src="'+state.animalPhotoData+'" alt="Vorschau">';el("animalReferenceNote").textContent="Eigenes Beobachtungsfoto."}catch(e){globalError(e.message)}});
el("animalForm").addEventListener("submit",function(e){e.preventDefault();saveAnimal(false)});
el("saveAnimalAndPlaceBtn").addEventListener("click",function(){saveAnimal(true)});
document.addEventListener("click",function(e){if(!(e.target.closest&&e.target.closest(".tax-search-field")))hideAnimalTaxonResults()});
'''
rep('el("closePlantEditor").addEventListener("click",function(){show("plantEditor",false)});',events+'\nel("closePlantEditor").addEventListener("click",function(){show("plantEditor",false)});','new events')
rep('el("clearBtn").addEventListener("click",function(){if(confirm("Alle Pflanzen, Zonen und Pflegehistorien löschen?")){state.plants=[];state.zones=[];save();renderAll();notice("Gartendaten gelöscht.")}});', 'el("clearBtn").addEventListener("click",function(){if(confirm("Alle Pflanzen, Lebensräume, Tierbeobachtungen, Zonen und Pflegehistorien löschen?")){state.plants=[];state.habitats=[];state.animals=[];state.zones=[];save();renderAll();notice("Gartendaten gelöscht.")}});','clear')

# Ensure opening plant editor selects plant pane
rep('el("newPlantBtn").addEventListener("click",function(){openPlantEditor(null)});','el("newPlantBtn").addEventListener("click",function(){setNatureTab("plants");openPlantEditor(null)});','new plant event')

# Validate essential markers
for marker in ['id="natureTabs"','id="natureHabitatsPane"','id="natureAnimalsPane"','function searchInaturalistTaxa','function habitatCollectionScore','function nativePlantStatus','version:3','iNaturalist']:
    if marker not in s:
        raise SystemExit('missing final marker '+marker)

p.write_text(s,encoding='utf-8')
print('updated index.html',len(orig),'->',len(s))
