from pathlib import Path
p=Path('setup.html')
s=p.read_text(encoding='utf-8')
s=s.replace('Auf dem neuen iPhone oder iPad mit der Kamera scannen. Danach führt die Seite durch die Einrichtung als Home-Screen-App.','Auf dem neuen iPhone oder iPad mit der Kamera scannen. <b>Wichtig:</b> Öffnet sich danach eine Vorschau mit einem Kompass-Symbol unten rechts, zuerst auf den Kompass tippen und die Seite im echten Safari öffnen. Erst dort zum Home-Bildschirm hinzufügen.')
s=s.replace('<div class="installhero"><b>Wichtig:</b> Die PIN jetzt noch nicht eingeben. Zuerst diese Seite zum Home-Bildschirm hinzufügen und <b>„Als Web-App öffnen“ eingeschaltet lassen</b>. Danach ausschließlich das neue Gartenwelt-Symbol auf dem Home-Bildschirm öffnen. <b>Wenn oben noch eine Internetadresse oder unten Safari-Schaltflächen sichtbar sind, bist du noch im Browser und nicht in der Web-App.</b></div>','<div class="installhero"><b>Wichtig:</b> Wenn unten rechts ein <b>Kompass-Symbol</b> sichtbar ist, bist du noch in der QR-/In-App-Vorschau. <b>Zuerst auf den Kompass tippen und in Safari öffnen.</b> Erst dort die Seite zum Home-Bildschirm hinzufügen und <b>„Als Web-App öffnen“ eingeschaltet lassen</b>. Danach ausschließlich das neue Gartenwelt-Symbol auf dem Home-Bildschirm öffnen.</div>')
old='''      <div class="step"><div class="stepno">1</div><div class="steptext">In Safari unten auf <b>Teilen</b> tippen.</div></div>\n      <div class="step"><div class="stepno">2</div><div class="steptext"><b>Zum Home-Bildschirm</b> auswählen.</div></div>\n      <div class="step"><div class="stepno">3</div><div class="steptext"><b>Als Web-App öffnen</b> eingeschaltet lassen.</div></div>\n      <div class="step"><div class="stepno">4</div><div class="steptext"><b>Hinzufügen</b> bestätigen.</div></div>\n      <div class="step"><div class="stepno">5</div><div class="steptext">Danach das neue Symbol <b>Johanna´s Gartenwelt</b> auf dem Home-Bildschirm öffnen.</div></div>\n      <div class="step"><div class="stepno">6</div><div class="steptext">Dort einmal die <b>Garten-PIN</b> eingeben. Danach sind Garten, Sync und PlantNet dauerhaft in der Home-Screen-App eingerichtet.</div></div>'''
new='''      <div class="step"><div class="stepno">1</div><div class="steptext">Nach dem QR-Scan: Ist unten rechts ein <b>Kompass-Symbol</b> sichtbar, darauf tippen. Dadurch öffnet sich die Seite im echten Safari.</div></div>\n      <div class="step"><div class="stepno">2</div><div class="steptext">Erst jetzt in Safari auf <b>Teilen</b> tippen.</div></div>\n      <div class="step"><div class="stepno">3</div><div class="steptext"><b>Zum Home-Bildschirm</b> auswählen.</div></div>\n      <div class="step"><div class="stepno">4</div><div class="steptext"><b>Als Web-App öffnen</b> eingeschaltet lassen.</div></div>\n      <div class="step"><div class="stepno">5</div><div class="steptext"><b>Hinzufügen</b> bestätigen.</div></div>\n      <div class="step"><div class="stepno">6</div><div class="steptext">Safari verlassen und das neue Symbol <b>Johanna´s Gartenwelt</b> auf dem Home-Bildschirm öffnen.</div></div>\n      <div class="step"><div class="stepno">7</div><div class="steptext">Dort einmal die <b>Garten-PIN</b> eingeben. Danach sind Garten, Sync und PlantNet dauerhaft in der Home-Screen-App eingerichtet.</div></div>'''
if old not in s: raise SystemExit('steps block not found')
s=s.replace(old,new)
p.write_text(s,encoding='utf-8')
print('patched')