from pathlib import Path
import re
p=Path('index.html'); s=p.read_text(encoding='utf-8')

def rep(old,new,label):
    global s
    if old not in s: raise SystemExit('missing '+label)
    s=s.replace(old,new,1)

if '/* JGW UX V3 */' in s:
    print('UI V3 already present'); raise SystemExit(0)

rep('<title>Johanna´s Gartenwelt</title>','''<title>Johanna´s Gartenwelt</title>\n<link rel="manifest" href="./manifest.webmanifest">\n<link rel="icon" href="./icon.svg" type="image/svg+xml">\n<link rel="apple-touch-icon" href="./apple-touch-icon.png">\n<meta name="apple-mobile-web-app-capable" content="yes">\n<meta name="apple-mobile-web-app-title" content="Johanna´s Gartenwelt">''','head links')

css=r'''
/* JGW UX V3 */
.app-toast{position:fixed;left:50%;bottom:max(18px,env(safe-area-inset-bottom));transform:translateX(-50%) translateY(16px);z-index:9200;max-width:min(560px,calc(100vw - 28px));padding:11px 15px;border-radius:16px;background:#405d43;color:#fff;box-shadow:0 14px 34px rgba(40,35,31,.24);font-size:13px;line-height:1.4;opacity:0;pointer-events:none;transition:opacity .2s ease,transform .2s ease}.app-toast.show{opacity:1;transform:translateX(-50%) translateY(0)}.app-toast.error-toast{background:#8b4642}
.onboarding-card{border-style:dashed}.guide-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px;margin-top:12px}.guide-step{border:1px solid var(--line);border-radius:15px;padding:12px;background:rgba(255,255,255,.67)}.guide-step.done{background:var(--ok);opacity:.76}.guide-step b{display:block;color:var(--forest-dark);margin-bottom:4px}.guide-mark{font-size:19px;float:right;margin-left:6px}.guide-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}
.plant-advanced{border:1px solid var(--line);border-radius:14px;padding:0;background:rgba(250,247,241,.72)}.plant-advanced>summary{padding:11px 13px;list-style:none}.plant-advanced>summary::-webkit-details-marker{display:none}.plant-advanced>summary:after{content:"＋";float:right;font-weight:400}.plant-advanced[open]>summary:after{content:"−"}.advanced-grid{padding:2px 12px 13px}
.plantcard{cursor:pointer;overflow:visible}.plantphoto{border-radius:18px 18px 0 0}.plant-openhint{font-size:11px;color:var(--muted);margin-top:7px}.card-menu{position:relative}.card-menu>summary{list-style:none}.card-menu>summary::-webkit-details-marker{display:none}.card-menu-pop{position:absolute;right:0;top:calc(100% + 6px);z-index:30;display:grid;gap:6px;min-width:170px;padding:8px;border:1px solid var(--line);border-radius:13px;background:var(--paper);box-shadow:0 14px 30px rgba(54,49,44,.18)}.card-menu-pop .btn{width:100%;text-align:left}
.calendar-more,.calendar-caption{display:none}
@media(max-width:700px){body{padding-bottom:calc(74px + env(safe-area-inset-bottom))}.wrap{padding-bottom:18px}.head{padding-bottom:13px}.tabs{position:fixed;left:0;right:0;bottom:0;z-index:4300;display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:2px;margin:0;padding:6px max(6px,env(safe-area-inset-right)) calc(6px + env(safe-area-inset-bottom)) max(6px,env(safe-area-inset-left));background:rgba(255,253,249,.94);border-top:1px solid var(--line);box-shadow:0 -8px 26px rgba(54,49,44,.10);backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px);overflow:visible}.tab{min-width:0;border:0;background:transparent;box-shadow:none;border-radius:12px;padding:6px 2px 5px;font-size:11px;line-height:1.15;display:grid;place-items:center;gap:2px;color:var(--muted)}.tab:before{display:block;font-size:18px;line-height:1;height:20px;color:var(--forest-dark)}.tab[data-view="today"]:before{content:"⌂"}.tab[data-view="plants"]:before{content:"🌿"}.tab[data-view="map"]:before{content:"⌖"}.tab[data-view="calendar"]:before{content:"▦"}.tab[data-view="weather"]:before{content:"☁"}.tab.active{background:var(--ok);color:var(--forest-dark);font-weight:800}.brand h1{font-size:25px}.brandtools{gap:6px}.locpill,.seasonmark{display:none!important}.syncmini,.quickbtn,.gearbtn{width:38px;height:38px}.syncmini{padding:0;justify-content:center}.syncmini-label{display:none}.app-toast,.undo-toast{bottom:calc(76px + env(safe-area-inset-bottom))}.guide-grid{grid-template-columns:1fr}.calendar.calendar-collapsed .calmonth:nth-child(n+4){display:none}.calendar-more{display:inline-flex}.calendar-caption{display:block}.card-menu-pop{right:-4px}}
'''
rep('@media(max-width:850px)',css+'\n@media(max-width:850px)','css')

rep('''  <div class="box">\n    <div class="topline"><h3>Heute zu tun</h3><span class="muted" id="taskCount"></span></div>''','''  <div class="box onboarding-card hidden" id="firstRunGuide">\n    <div class="topline"><div><h3>Erste Schritte</h3><div class="muted">Drei kurze Schritte – danach verschwindet diese Hilfe automatisch.</div></div><button class="btn ghost small" id="guideDismissBtn" type="button">Später</button></div>\n    <div class="guide-grid">\n      <div class="guide-step" id="guideLocation"><span class="guide-mark">1</span><b>Standort</b><div class="muted">PLZ für Wetter und Gießempfehlungen.</div><div class="guide-actions"><button class="btn secondary small" id="guideLocationBtn" type="button">Standort einrichten</button></div></div>\n      <div class="guide-step" id="guideMap"><span class="guide-mark">2</span><b>Garten</b><div class="muted">Einmal den passenden Luftbildausschnitt speichern.</div><div class="guide-actions"><button class="btn secondary small" id="guideMapBtn" type="button">Gartenausschnitt</button></div></div>\n      <div class="guide-step" id="guidePlant"><span class="guide-mark">3</span><b>Erste Pflanze</b><div class="muted">Foto und Name reichen für den Start.</div><div class="guide-actions"><button class="btn secondary small" id="guidePlantBtn" type="button">Pflanze hinzufügen</button></div></div>\n    </div>\n  </div>\n  <div class="box">\n    <div class="topline"><h3>Heute zu tun</h3><span class="muted" id="taskCount"></span></div>''','guide')

pat=re.compile(r'        <div class="field"><label for="plantScientific">Botanischer Name</label>.*?        <div class="field full"><label for="plantNotes">Notizen</label><textarea id="plantNotes".*?</textarea></div>',re.S)
new='''        <div class="field"><label for="plantArea">Gartenbereich</label><input id="plantArea" placeholder="z. B. Vorgarten"></div>\n        <details class="plant-advanced field full"><summary>Weitere Angaben <span class="muted">optional</span></summary><div class="formgrid advanced-grid">\n          <div class="field"><label for="plantScientific">Botanischer Name</label><input id="plantScientific" placeholder="z. B. Hydrangea macrophylla"></div>\n          <div class="field"><label for="plantType">Pflanzung</label><select id="plantType"><option value="bed" selected>Direkt im Gartenboden (Standard)</option><option value="pot">Kübel / Topf</option><option value="raised">Hochbeet</option><option value="balcony">Balkonkasten</option><option value="other">Sonstige Pflanzung</option></select></div>\n          <div class="field"><label for="plantWater">Wasserbedarf</label><select id="plantWater"><option value="low">Niedrig</option><option value="normal" selected>Normal</option><option value="high">Hoch</option></select></div>\n          <div class="field"><label for="plantSize">Pflanzengröße</label><select id="plantSize"><option value="small">Klein</option><option value="medium" selected>Mittel</option><option value="large">Groß</option></select></div>\n          <div class="field"><label for="plantBirthYear">Pflanz-/Anzuchtjahr (ca.)</label><input id="plantBirthYear" type="number" inputmode="numeric" min="1900" max="2100" placeholder="z. B. 2024"></div>\n          <div class="field"><label for="plantSince">Am aktuellen Standort seit</label><input id="plantSince" type="date"></div>\n          <div class="field"><label for="plantTransplanted">Zuletzt umgepflanzt / umgetopft</label><input id="plantTransplanted" type="date"></div>\n          <div class="field"><label for="plantOrgan">Foto zeigt</label><select id="plantOrgan"><option value="auto">Automatisch</option><option value="leaf">Blatt</option><option value="flower">Blüte</option><option value="fruit">Frucht</option><option value="bark">Rinde</option><option value="habit">Gesamtpflanze</option></select></div>\n          <div class="field full"><label>Düngemonate</label><div class="monthrow" id="fertMonths"></div></div>\n          <div class="field full"><label>Schnittmonate</label><div class="monthrow" id="cutMonths"></div></div>\n          <div class="field full"><label for="plantNotes">Notizen</label><textarea id="plantNotes" placeholder="Besonderheiten, Sorte, Pflanzjahr …"></textarea></div>\n        </div></details>'''
s,n=pat.subn(new,s,1)
if n!=1: raise SystemExit('plant form pattern')

rep('''        <button class="btn secondary" id="fitGardenBtn" type="button">Alles anzeigen</button>\n        <button class="btn ghost" id="setGardenCenterBtn" type="button">Gartenmitte setzen</button>''','''        <button class="btn secondary" id="fitGardenBtn" type="button">Alles anzeigen</button>''','map center')
rep('<button class="btn ghost small" id="openMapEditor" type="button">Gartenausschnitt ändern</button><button class="btn ghost small" id="openGardenCenter" type="button">Gartenmitte setzen</button>','<button class="btn ghost small" id="openMapEditor" type="button">Gartenausschnitt ändern</button>','settings center')
rep('Für Wetter und Gießempfehlungen genügt die Postleitzahl. Die genaue Gartenmitte kann bei Bedarf auf der Karte gesetzt werden.','Für Wetter und Gießempfehlungen genügt die Postleitzahl. Die Mitte des gespeicherten Gartenausschnitts wird automatisch als genaue Wetterposition verwendet.','location help')
rep('<b>Gartenausschnitt einmal festlegen:</b> Karte verschieben und zoomen, bis dein Garten gut sichtbar ist. Danach „Ausschnitt speichern“ wählen.','<b>Gartenausschnitt einmal festlegen:</b> Karte verschieben und zoomen, bis dein Garten gut sichtbar ist. Beim Speichern wird die Kartenmitte zugleich als Wetterposition übernommen.','map help')
rep('<div class="calendar" id="calendarGrid" style="margin-top:15px"></div>','<div class="muted calendar-caption" style="margin-top:14px">Zuerst siehst du die nächsten drei Monate.</div><div class="calendar calendar-collapsed" id="calendarGrid" style="margin-top:15px"></div><div style="margin-top:12px"><button class="btn ghost small calendar-more" id="calendarMoreBtn" type="button">Ganzes Pflegejahr anzeigen</button></div>','calendar')
rep('<div id="globalNotice" class="box notice hidden"></div>','<div id="globalNotice" class="box notice hidden"></div>\n<div id="appToast" class="app-toast" role="status" aria-live="polite"></div>','toast')

p.write_text(s,encoding='utf-8'); print('UX3 UI patched')
